"""Reasoning Path Execution Engine implementation for E-PATH-CO-REASON."""

from __future__ import annotations

import torch
import torch.nn as nn

from models.emergent_path_triage.config import EmergentPathTriageConfig
from models.emergent_path_triage.exceptions import InterfaceError, RoutingError
from models.emergent_path_triage.interfaces import BaseClinicalThoughtBlock
from models.emergent_path_triage.logger import get_logger
from models.emergent_path_triage.types import RoutingDecision, ThoughtPath

logger = get_logger()


class ReasoningPathExecutionEngine(nn.Module):
    """Orchestrates dynamic reasoning path execution through CTBs.
    
    Transforms the latent patient complaint representations according to 
    the dynamic path routing decisions made by DCRR.
    
    ============================================================================
    REASONING FLOW & MATH CORRESPONDENCE
    ============================================================================
    1. Initial State Formulation:
       The initial representation is defined as the mean across the four aspect
       evidence embeddings generated by DCES:
           h_0 = Mean(E) = 1/4 * (E_sym + E_loc + E_temp + E_sys)
       where h_0 in R^{B x d}.
       
    2. Dynamic Sequential Path Updates:
       At each step m in {1, ..., M}, we update the state:
       - Training Mode (differentiable soft blend):
           h_m = sum_{j=1}^N Z_{m, j} * CTB_j(h_{m-1})
         where Z_{m, j} is the Gumbel-Softmax probability matrix element.
       - Inference Mode (hard conditional execution):
           h_m = CTB_{k_m}(h_{m-1})
         where k_m = selected_blocks[m] is the argmax routing index for step m.
         This guarantees that only the selected block is executed, keeping the
         computational cost constant at O(M * TF_Layer) regardless of total blocks N.
         
    ============================================================================
    COMPUTATIONAL COMPLEXITY
    ============================================================================
    Time Complexity:
    - Inference: O(B * M * d * H_ctb) -> Executes exactly M blocks.
    - Training:  O(B * M * N * d * H_ctb) -> Executes all N blocks to blend gradients.
    Space Complexity:
    - O(B * M * d) to allocate memory for the intermediate state path.
    """

    def __init__(self, config: EmergentPathTriageConfig) -> None:
        super().__init__()
        self.config = config
        logger.info(
            f"Initialized ReasoningPathExecutionEngine with max_path_depth={config.max_path_depth}, "
            f"num_thought_blocks={config.num_thought_blocks}"
        )

    def forward(
        self,
        evidence_list: list[torch.Tensor],
        routing_decision: RoutingDecision,
        blocks: nn.ModuleList
    ) -> tuple[torch.Tensor, ThoughtPath]:
        """Orchestrate path execution through selected Clinical Thought Blocks.
        
        Args:
            evidence_list: List of the 4 aspect evidence tensors: [symptom, anatomical, temporal, systemic]
                Each aspect tensor of shape (Batch, Latent_Dim).
            routing_decision: Decided routing path from DCRR.
            blocks: Active thought blocks collection.
            
        Returns:
            final_state: The final transformed latent embedding: (Batch, Latent_Dim).
            thought_path: Strongly typed ThoughtPath tracking step-wise representations.
        """
        # 1. Verification and validations
        if not isinstance(routing_decision, RoutingDecision):
            raise InterfaceError(
                f"Execution engine expects a RoutingDecision instance, got {type(routing_decision)}"
            )
        
        if len(evidence_list) != 4:
            raise InterfaceError(f"Expected exactly 4 aspect evidence tensors, got {len(evidence_list)}")

        device = evidence_list[0].device
        latent_dim = evidence_list[0].shape[1]
        batch_size = evidence_list[0].shape[0]

        # Verify all aspects match shape, dtype, and device
        for i, tensor in enumerate(evidence_list):
            if not isinstance(tensor, torch.Tensor):
                raise InterfaceError(f"Evidence aspect {i} must be a torch.Tensor")
            if tensor.device != device:
                raise InterfaceError(f"Device mismatch: Aspect {i} on {tensor.device} vs {device}")
            if tensor.dtype != torch.float32:
                amp_enabled = torch.is_autocast_enabled()
                ckpt_precision = getattr(self.config, "checkpoint_precision_mode", "Unknown")
                raise InterfaceError(
                    f"Incorrect dtype: Aspect {i} must be float32, got {tensor.dtype}.\n"
                    f"Diagnostics:\n"
                    f"  Module: ReasoningPathExecutionEngine\n"
                    f"  Tensor Name: evidence_list[{i}]\n"
                    f"  Shape: {tensor.shape}\n"
                    f"  Device: {tensor.device}\n"
                    f"  Expected dtype: torch.float32\n"
                    f"  Actual dtype: {tensor.dtype}\n"
                    f"  Previous module: ClinicalEvidenceSynthesizer (DCES)\n"
                    f"  Current module: ReasoningPathExecutionEngine\n"
                    f"  Checkpoint precision mode: {ckpt_precision}\n"
                    f"  AMP enabled status: {amp_enabled}"
                )
            if len(tensor.shape) != 2:
                raise InterfaceError(f"Aspect {i} must be 2D of shape (Batch, Latent_Dim), got {tensor.shape}")
            if tensor.shape[0] != batch_size or tensor.shape[1] != latent_dim:
                raise InterfaceError(
                    f"Shape mismatch at aspect {i}: expected ({batch_size}, {latent_dim}), got {tensor.shape}"
                )

        # Verify blocks collection
        if len(blocks) != self.config.num_thought_blocks:
            raise InterfaceError(
                f"Blocks count mismatch: config specifies {self.config.num_thought_blocks} "
                f"but received {len(blocks)} blocks"
            )
        for idx, block in enumerate(blocks):
            if not isinstance(block, BaseClinicalThoughtBlock):
                raise InterfaceError(f"Block at index {idx} does not inherit from BaseClinicalThoughtBlock")

        # Verify routing bounds
        if routing_decision.path_depth != self.config.max_path_depth:
            raise RoutingError(
                f"Routing path depth mismatch: DCRR produced depth {routing_decision.path_depth} "
                f"but config requires {self.config.max_path_depth}"
            )
        
        # Verify block index ranges in the selected blocks
        for idx, step_idx in enumerate(routing_decision.selected_blocks):
            if not (0 <= step_idx < self.config.num_thought_blocks):
                raise RoutingError(
                    f"Invalid block selection: Selected index {step_idx} at step {idx} "
                    f"is out of bounds for {self.config.num_thought_blocks} blocks"
                )

        # 2. Formulate Initial State h_0 = Mean(E)
        # Stack to (Batch, 4, Latent_Dim) and take mean over dimension 1
        stacked_evidence = torch.stack(evidence_list, dim=1)
        h_0 = torch.mean(stacked_evidence, dim=1)

        # State path tracker
        representations = [h_0]
        current_state = h_0

        # 3. Path Execution Loop
        if self.training:
            # Differentiable soft path routing during training
            for m in range(self.config.max_path_depth):
                # Retrieve the probabilities for step m: (Batch, Num_Blocks)
                step_probs = routing_decision.routing_probabilities[:, m, :]
                
                # Execute all blocks on the current state
                # List of (Batch, Latent_Dim) tensors
                updated_states_list = [block(current_state) for block in blocks]
                
                # Stack to (Batch, Num_Blocks, Latent_Dim)
                stacked_updates = torch.stack(updated_states_list, dim=1)
                
                # Multiply by Gumbel probabilities along the blocks dimension
                # (Batch, Num_Blocks, Latent_Dim) * (Batch, Num_Blocks, 1) -> sum along blocks
                next_state = torch.sum(stacked_updates * step_probs.unsqueeze(-1), dim=1)
                
                # Append state
                representations.append(next_state)
                current_state = next_state
        else:
            # Deterministic, optimized hard routing during inference (zero unused blocks execution)
            for m in range(self.config.max_path_depth):
                selected_block_idx = routing_decision.selected_blocks[m]
                
                # Only execute the selected thought block to preserve parameter footprint
                next_state = blocks[selected_block_idx](current_state)
                
                representations.append(next_state)
                current_state = next_state

        # 4. Construct ThoughtPath dataclass
        thought_path = ThoughtPath(
            states=routing_decision.selected_blocks,
            representations=representations
        )

        return current_state, thought_path
