from .chatdoctor_healthcaremagic import ChatdoctorHealthcaremagicAdapter
from .chatdoctor_icliniq import ChatdoctorIcliniqAdapter
from .medical_meadow_medqa import MedicalMeadowMedqaAdapter
from .medqa_usmle import MedqaUsmleAdapter
from .mtsamples import MtsamplesAdapter
from .neiss import NeissAdapter
from .pmc_patients import PmcPatientsAdapter
from .symptom2disease import Symptom2diseaseAdapter