"""Clinical Quality Validator for Multilingual Dataset Expansion.

Validates that expanded clinical texts preserve medical intent, symptoms,
severity, numbers, and script expectations while filtering out refusals
or severe hallucinations.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any


@dataclass
class ValidationResult:
    """Result of clinical quality validation."""

    passed: bool
    reason: str = ""
    language: str = ""
    metrics: dict[str, Any] = field(default_factory=dict)


class ClinicalQualityValidator:
    """Validates clinical text quality and semantic preservation."""

    # Refusal markers commonly generated by overly cautious LLMs
    REFUSAL_MARKERS = (
        "i am sorry",
        "as an ai",
        "i cannot help",
        "i can't provide",
        "medical advice",
        "consult a doctor",
        "not appropriate",
        "i am unable to",
    )

    # Core medical/symptom terms dictionary mapping English to Hindi / Hinglish roots
    CLINICAL_ROOTS = {
        "chest": ["chest", "छाती", "सीना", "cheest", "seena", "chaati"],
        "pain": ["pain", "दर्द", "दर्द", "dard", "paain"],
        "breath": ["breath", "साँस", "सांस", "saans", "sans", "breathing"],
        "fever": ["fever", "बुखार", "bukhar", "fevar"],
        "cough": ["cough", "खाँसी", "खांसी", "khansi", "kaap"],
        "headache": ["headache", "सिरदर्द", "सर दर्द", "headache", "sirdard", "sardard"],
        "stomach": ["stomach", "पेट", "pet", "stomach"],
        "vomit": ["vomit", "उल्टी", "ulti", "vomiting"],
        "dizzy": ["dizzy", "चक्कर", "chakkar", "dizziness"],
        "swelling": ["swelling", "सूजन", "sujan", "soojan"],
        "injury": ["injury", "चोट", "chot", "injuri"],
        "fracture": ["fracture", "हड्डी टूट", "fracture", "haaddi", "toot"],
        "bleeding": ["bleeding", "खून", "khoon", "bleeding"],
    }

    def __init__(self, min_length: int = 5, max_length_ratio: float = 3.5):
        self.min_length = min_length
        self.max_length_ratio = max_length_ratio

    def validate(
        self,
        source_text: str,
        target_text: str,
        target_lang: str,
        department: str | None = None,
        triage_level: str | None = None,
    ) -> ValidationResult:
        """Validate a generated translation against the source text.

        Args:
            source_text: Original English text.
            target_text: Generated translation text.
            target_lang: Language code ('en', 'hi', 'hi-Latn', 'hi-en', 'en-hi').
            department: Expected department label (optional).
            triage_level: Expected triage level (optional).

        Returns:
            ValidationResult instance.
        """
        # 1. Non-null and min length check
        if not target_text or not isinstance(target_text, str):
            return ValidationResult(passed=False, reason="Empty or null text", language=target_lang)

        target_clean = target_text.strip()
        if len(target_clean) < self.min_length:
            return ValidationResult(passed=False, reason="Text too short", language=target_lang)

        # 2. Refusal detection
        target_lower = target_clean.lower()
        for marker in self.REFUSAL_MARKERS:
            if marker in target_lower:
                return ValidationResult(
                    passed=False,
                    reason=f"Refusal marker detected: '{marker}'",
                    language=target_lang,
                )

        # 3. Script validation
        if target_lang == "hi":
            # Must contain Devanagari script (\u0900-\u097F)
            if not re.search(r"[\u0900-\u097F]", target_clean):
                return ValidationResult(
                    passed=False,
                    reason="Missing Devanagari script for Hindi",
                    language=target_lang,
                )
        elif target_lang in ("hi-Latn", "hi-en", "en-hi", "en"):
            # Must contain Latin characters
            if not re.search(r"[a-zA-Z]", target_clean):
                return ValidationResult(
                    passed=False,
                    reason=f"Missing Latin script for language '{target_lang}'",
                    language=target_lang,
                )

        # 4. Length ratio check (Hallucination / Truncation check)
        if len(source_text) > 0:
            ratio = len(target_clean) / float(len(source_text))
            if ratio < 0.25:
                return ValidationResult(
                    passed=False,
                    reason=f"Text truncated (length ratio {ratio:.2f} < 0.25)",
                    language=target_lang,
                )
            if ratio > self.max_length_ratio:
                return ValidationResult(
                    passed=False,
                    reason=f"Possible hallucination (length ratio {ratio:.2f} > {self.max_length_ratio})",
                    language=target_lang,
                )

        # 5. Number preservation check
        # Extract digits / numbers from source (e.g. 102, 3, 24)
        source_numbers = set(re.findall(r"\d+", source_text))
        if source_numbers:
            target_numbers = set(re.findall(r"\d+", target_clean))
            # Also check Devanagari numbers if target is Hindi (०-९)
            devanagari_digits = {"०": "0", "१": "1", "२": "2", "३": "3", "४": "4",
                                 "५": "5", "६": "6", "७": "7", "८": "8", "९": "9"}
            dev_translated = ""
            for ch in target_clean:
                if ch in devanagari_digits:
                    dev_translated += devanagari_digits[ch]
                elif ch.isdigit():
                    dev_translated += ch
                else:
                    dev_translated += " "
            target_numbers.update(re.findall(r"\b\d+\b", dev_translated))

            # At least the important numbers (temperature, age, vitals) should be present
            missing_nums = source_numbers - target_numbers
            if len(missing_nums) > len(source_numbers) // 2 and len(source_numbers) <= 3:
                return ValidationResult(
                    passed=False,
                    reason=f"Numerical discrepancy: missing numbers {missing_nums}",
                    language=target_lang,
                )

        # 6. Clinical term matching score
        matched_roots = 0
        source_lower = source_text.lower()
        for root_key, variants in self.CLINICAL_ROOTS.items():
            if root_key in source_lower or any(v in source_lower for v in variants if v.isascii()):
                # Source has this symptom root, check if target has any variant
                if any(v in target_lower for v in variants):
                    matched_roots += 1

        return ValidationResult(
            passed=True,
            reason="Passed clinical quality checks",
            language=target_lang,
            metrics={
                "length_ratio": round(len(target_clean) / max(len(source_text), 1), 2),
                "matched_clinical_roots": matched_roots,
            },
        )
