"""
Core data structures for the Research Experiment Framework (REF).

This module provides strictly validated, deterministically ordered,
and serializable data structures for orchestrating research experiments.
"""

import hashlib
import json
from dataclasses import asdict, dataclass, field
from datetime import datetime
from typing import Any


class SchemaValidationError(Exception):
    """Raised when an artifact fails schema validation."""


def _deterministic_hash(data: dict[str, Any]) -> str:
    """Generate a stable SHA-256 hash of a dictionary by sorting keys."""
    sorted_json = json.dumps(data, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(sorted_json.encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class ExperimentMetadata:
    """Core identity and contextual metadata of the experiment."""

    experiment_id: str
    experiment_name: str
    hypothesis: str
    modules_enabled: dict[str, bool]
    dataset: str
    seed: int
    execution_timestamp: str = field(
        default_factory=lambda: datetime.utcnow().isoformat()
    )
    environment_hash: str = ""

    def validate(self) -> None:
        if not self.experiment_id or not self.experiment_name:
            raise SchemaValidationError("Experiment ID and Name are strictly required.")
        if not isinstance(self.modules_enabled, dict):
            raise SchemaValidationError("modules_enabled must be a dictionary.")

    def to_dict(self) -> dict[str, Any]:
        """Serialize with deterministic key ordering."""
        d = asdict(self)
        return dict(sorted(d.items()))

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ExperimentMetadata":
        return cls(**data)


@dataclass(frozen=True)
class ExperimentConfiguration:
    """Frozen hyperparameter and operational configuration state."""

    config_overrides: dict[str, Any]
    checkpoint_reference: str | None = None
    configuration_hash: str = field(init=False)

    def __post_init__(self):
        # We compute a hash of the configuration for reproducibility mapping
        hash_val = _deterministic_hash(self.config_overrides)
        object.__setattr__(self, "configuration_hash", hash_val)

    def validate(self) -> None:
        if not isinstance(self.config_overrides, dict):
            raise SchemaValidationError("config_overrides must be a dictionary.")

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        return dict(sorted(d.items()))

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ExperimentConfiguration":
        # Extract fields to bypass the init=False conflict for configuration_hash
        overrides = data.get("config_overrides", {})
        chkpt = data.get("checkpoint_reference", None)
        return cls(config_overrides=overrides, checkpoint_reference=chkpt)


@dataclass(frozen=True)
class ExperimentMetrics:
    """Aggregated numerical evaluations resulting from execution."""

    clinical: dict[str, float] = field(default_factory=dict)
    calibration: dict[str, float] = field(default_factory=dict)
    routing: dict[str, float] = field(default_factory=dict)
    optimization: dict[str, float] = field(default_factory=dict)
    confidence: dict[str, float] = field(default_factory=dict)
    efficiency: dict[str, float] = field(default_factory=dict)

    def validate(self) -> None:
        for domain, metrics in asdict(self).items():
            if not isinstance(metrics, dict):
                raise SchemaValidationError(
                    f"Metric domain {domain} must be a dictionary."
                )
            for k, v in metrics.items():
                if not isinstance(v, (int, float)):
                    raise SchemaValidationError(
                        f"Metric {domain}.{k} must be numerical."
                    )

    def to_dict(self) -> dict[str, Any]:
        """Deep deterministic sorting for all metric domains."""
        d = asdict(self)
        return {k: dict(sorted(v.items())) for k, v in sorted(d.items())}

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ExperimentMetrics":
        return cls(
            clinical=data.get("clinical", {}),
            calibration=data.get("calibration", {}),
            routing=data.get("routing", {}),
            optimization=data.get("optimization", {}),
            confidence=data.get("confidence", {}),
            efficiency=data.get("efficiency", {}),
        )


@dataclass(frozen=True)
class ExperimentArtifacts:
    """Pointers to files generated by the experiment."""

    output_dir: str
    checkpoint_paths: list[str] = field(default_factory=list)
    plot_paths: list[str] = field(default_factory=list)
    table_paths: list[str] = field(default_factory=list)

    def validate(self) -> None:
        if not self.output_dir:
            raise SchemaValidationError("output_dir is required.")

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        return dict(sorted(d.items()))

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ExperimentArtifacts":
        return cls(**data)


@dataclass(frozen=True)
class ExperimentSummary:
    """Human-readable abstract outlining final results."""

    status: str
    conclusion: str
    key_metrics: dict[str, float] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)

    def validate(self) -> None:
        valid_statuses = {"COMPLETED", "FAILED", "ABORTED"}
        if self.status not in valid_statuses:
            raise SchemaValidationError(f"Status must be one of {valid_statuses}")

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        return dict(sorted(d.items()))

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ExperimentSummary":
        return cls(**data)


@dataclass(frozen=True)
class ExperimentReport:
    """Comprehensive compilation combining all artifacts into a singular structure."""

    metadata: ExperimentMetadata
    configuration: ExperimentConfiguration
    metrics: ExperimentMetrics
    artifacts: ExperimentArtifacts
    summary: ExperimentSummary

    def validate(self) -> None:
        self.metadata.validate()
        self.configuration.validate()
        self.metrics.validate()
        self.artifacts.validate()
        self.summary.validate()

    def to_dict(self) -> dict[str, Any]:
        d = {
            "metadata": self.metadata.to_dict(),
            "configuration": self.configuration.to_dict(),
            "metrics": self.metrics.to_dict(),
            "artifacts": self.artifacts.to_dict(),
            "summary": self.summary.to_dict(),
        }
        return dict(sorted(d.items()))

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ExperimentReport":
        return cls(
            metadata=ExperimentMetadata.from_dict(data.get("metadata", {})),
            configuration=ExperimentConfiguration.from_dict(
                data.get("configuration", {})
            ),
            metrics=ExperimentMetrics.from_dict(data.get("metrics", {})),
            artifacts=ExperimentArtifacts.from_dict(data.get("artifacts", {})),
            summary=ExperimentSummary.from_dict(data.get("summary", {})),
        )
