"""
Data structures for the REF Metrics Engine.

Provides strictly validated, deterministic data representations
for the metric evaluation lifecycle.
"""

from dataclasses import dataclass, field, asdict
from typing import Any, Union
import json
import hashlib

class MetricValidationError(Exception):
    """Raised when metric structures fail validation."""

def _deterministic_dict(d: dict[str, Any]) -> dict[str, Any]:
    """Ensure dictionaries are sorted for deterministic serialization."""
    return dict(sorted(d.items()))

@dataclass(frozen=True)
class MetricMetadata:
    """Metadata describing a specific metric or provider execution."""
    name: str
    version: str
    description: str
    dependencies: list[str] = field(default_factory=list)

    def validate(self) -> None:
        if not self.name or not self.version:
            raise MetricValidationError("MetricMetadata must specify name and version.")

    def to_dict(self) -> dict[str, Any]:
        return _deterministic_dict(asdict(self))

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "MetricMetadata":
        return cls(**data)


@dataclass(frozen=True)
class MetricResult:
    """A singular calculated metric value with optional context."""
    name: str
    value: Union[float, int, str, bool, list, dict]
    context: dict[str, Any] = field(default_factory=dict)

    def validate(self) -> None:
        if not self.name:
            raise MetricValidationError("MetricResult must have a name.")
        if self.value is None:
            raise MetricValidationError(f"MetricResult '{self.name}' value cannot be None.")

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["context"] = _deterministic_dict(d["context"])
        # We don't enforce order on list/dict values directly, but context is sorted
        return _deterministic_dict(d)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "MetricResult":
        return cls(**data)


@dataclass(frozen=True)
class MetricCollection:
    """A collection of results generated by a single provider or run."""
    provider_name: str
    results: dict[str, MetricResult] = field(default_factory=dict)

    def validate(self) -> None:
        if not self.provider_name:
            raise MetricValidationError("MetricCollection must have a provider_name.")
        for k, v in self.results.items():
            if not isinstance(v, MetricResult):
                raise MetricValidationError(f"Key {k} must map to a MetricResult.")
            v.validate()

    def to_dict(self) -> dict[str, Any]:
        d = {
            "provider_name": self.provider_name,
            "results": _deterministic_dict({k: v.to_dict() for k, v in self.results.items()})
        }
        return _deterministic_dict(d)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "MetricCollection":
        results = data.get("results", {})
        return cls(
            provider_name=data.get("provider_name", "unknown"),
            results={k: MetricResult.from_dict(v) for k, v in results.items()}
        )


@dataclass(frozen=True)
class MetricGroup:
    """A higher-level grouping of MetricCollections (e.g., 'Clinical', 'Optimization')."""
    group_name: str
    collections: dict[str, MetricCollection] = field(default_factory=dict)

    def validate(self) -> None:
        if not self.group_name:
            raise MetricValidationError("MetricGroup must have a group_name.")
        for k, v in self.collections.items():
            if not isinstance(v, MetricCollection):
                raise MetricValidationError(f"Key {k} must map to a MetricCollection.")
            v.validate()

    def to_dict(self) -> dict[str, Any]:
        d = {
            "group_name": self.group_name,
            "collections": _deterministic_dict({k: v.to_dict() for k, v in self.collections.items()})
        }
        return _deterministic_dict(d)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "MetricGroup":
        cols = data.get("collections", {})
        return cls(
            group_name=data.get("group_name", "unknown"),
            collections={k: MetricCollection.from_dict(v) for k, v in cols.items()}
        )


@dataclass(frozen=True)
class MetricReport:
    """The root output of the entire Metrics Engine pipeline."""
    experiment_id: str
    groups: dict[str, MetricGroup] = field(default_factory=dict)
    report_hash: str = field(init=False)

    def __post_init__(self):
        # Generate deterministic hash for the entire report
        d = self.to_dict()
        # Remove hash if calculating hash
        if "report_hash" in d:
            del d["report_hash"]
        sorted_json = json.dumps(d, sort_keys=True, separators=(',', ':'))
        hash_val = hashlib.sha256(sorted_json.encode('utf-8')).hexdigest()
        object.__setattr__(self, "report_hash", hash_val)

    def validate(self) -> None:
        if not self.experiment_id:
            raise MetricValidationError("MetricReport must specify experiment_id.")
        for k, v in self.groups.items():
            if not isinstance(v, MetricGroup):
                raise MetricValidationError(f"Key {k} must map to a MetricGroup.")
            v.validate()

    def to_dict(self) -> dict[str, Any]:
        d = {
            "experiment_id": self.experiment_id,
            "groups": _deterministic_dict({k: v.to_dict() for k, v in self.groups.items()})
        }
        if hasattr(self, "report_hash"):
            d["report_hash"] = getattr(self, "report_hash")
        return _deterministic_dict(d)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "MetricReport":
        groups = data.get("groups", {})
        obj = cls(
            experiment_id=data.get("experiment_id", "unknown"),
            groups={k: MetricGroup.from_dict(v) for k, v in groups.items()}
        )
        if "report_hash" in data:
            object.__setattr__(obj, "report_hash", data["report_hash"])
        return obj
