"""
Data structures for the REF Visualization Engine.

Provides strictly validated, deterministic data representations
for the visualization execution lifecycle.
"""

from dataclasses import dataclass, field, asdict
from typing import Any
import json
import hashlib
from pathlib import Path

class VisualizationValidationError(Exception):
    """Raised when visualization structures fail validation."""
    pass

def _deterministic_dict(d: dict[str, Any]) -> dict[str, Any]:
    """Ensure dictionaries are sorted for deterministic serialization."""
    return dict(sorted(d.items()))

@dataclass(frozen=True)
class VisualizationRequest:
    """The configuration and metric payload needed to render plots."""
    experiment_id: str
    output_dir: str
    metric_report_dict: dict[str, Any]
    config_overrides: dict[str, Any] = field(default_factory=dict)

    def validate(self) -> None:
        if not self.experiment_id:
            raise VisualizationValidationError("VisualizationRequest must specify experiment_id.")
        if not self.output_dir:
            raise VisualizationValidationError("VisualizationRequest must specify output_dir.")

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        return _deterministic_dict(d)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "VisualizationRequest":
        return cls(**data)


@dataclass(frozen=True)
class VisualizationMetadata:
    """Metadata describing a specific visualization provider or plot."""
    name: str
    version: str
    description: str
    dependencies: list[str] = field(default_factory=list)

    def validate(self) -> None:
        if not self.name or not self.version:
            raise VisualizationValidationError("VisualizationMetadata must specify name and version.")

    def to_dict(self) -> dict[str, Any]:
        return _deterministic_dict(asdict(self))

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "VisualizationMetadata":
        return cls(**data)


@dataclass(frozen=True)
class VisualizationArtifact:
    """Pointer to a rendered and exported plot."""
    name: str
    file_path: str
    format: str
    metadata: dict[str, Any] = field(default_factory=dict)

    def validate(self) -> None:
        if not self.name:
            raise VisualizationValidationError("VisualizationArtifact must have a name.")
        if not self.file_path:
            raise VisualizationValidationError("VisualizationArtifact must specify a file path.")

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["metadata"] = _deterministic_dict(d["metadata"])
        return _deterministic_dict(d)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "VisualizationArtifact":
        return cls(**data)


@dataclass(frozen=True)
class VisualizationCollection:
    """A collection of visualization artifacts generated by a single provider."""
    provider_name: str
    artifacts: dict[str, VisualizationArtifact] = field(default_factory=dict)

    def validate(self) -> None:
        if not self.provider_name:
            raise VisualizationValidationError("VisualizationCollection must have a provider_name.")
        for k, v in self.artifacts.items():
            if not isinstance(v, VisualizationArtifact):
                raise VisualizationValidationError(f"Key {k} must map to a VisualizationArtifact.")
            v.validate()

    def to_dict(self) -> dict[str, Any]:
        d = {
            "provider_name": self.provider_name,
            "artifacts": _deterministic_dict({k: v.to_dict() for k, v in self.artifacts.items()})
        }
        return _deterministic_dict(d)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "VisualizationCollection":
        artifacts = data.get("artifacts", {})
        return cls(
            provider_name=data.get("provider_name", "unknown"),
            artifacts={k: VisualizationArtifact.from_dict(v) for k, v in artifacts.items()}
        )


@dataclass(frozen=True)
class VisualizationReport:
    """The root output of the entire Visualization Engine pipeline."""
    experiment_id: str
    collections: dict[str, VisualizationCollection] = field(default_factory=dict)
    report_hash: str = field(init=False)

    def __post_init__(self):
        # Generate deterministic hash for the entire report
        d = self.to_dict()
        if "report_hash" in d:
            del d["report_hash"]
        sorted_json = json.dumps(d, sort_keys=True, separators=(',', ':'))
        hash_val = hashlib.sha256(sorted_json.encode('utf-8')).hexdigest()
        object.__setattr__(self, "report_hash", hash_val)

    def validate(self) -> None:
        if not self.experiment_id:
            raise VisualizationValidationError("VisualizationReport must specify experiment_id.")
        for k, v in self.collections.items():
            if not isinstance(v, VisualizationCollection):
                raise VisualizationValidationError(f"Key {k} must map to a VisualizationCollection.")
            v.validate()

    def to_dict(self) -> dict[str, Any]:
        d = {
            "experiment_id": self.experiment_id,
            "collections": _deterministic_dict({k: v.to_dict() for k, v in self.collections.items()})
        }
        if hasattr(self, "report_hash"):
            d["report_hash"] = getattr(self, "report_hash")
        return _deterministic_dict(d)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "VisualizationReport":
        collections = data.get("collections", {})
        obj = cls(
            experiment_id=data.get("experiment_id", "unknown"),
            collections={k: VisualizationCollection.from_dict(v) for k, v in collections.items()}
        )
        if "report_hash" in data:
            object.__setattr__(obj, "report_hash", data["report_hash"])
        return obj
