import json
from pathlib import Path

# Load original notebook structure
notebook_path = Path("EPATH_CO_REASON_Training.ipynb")
with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

cells = nb["cells"]
new_cells = []

# Helper to find code cell by contents
def find_code_cell(keyword):
    for cell in cells:
        if cell.get("code") == "code" or cell.get("cell_type") == "code":
            src = "".join(cell.get("source", []))
            if keyword in src:
                return cell
    raise ValueError(f"Could not find code cell containing keyword: '{keyword}'")

# Helper to find markdown cell by contents
def find_markdown_cell(keyword):
    for cell in cells:
        if cell.get("cell_type") == "markdown":
            src = "".join(cell.get("source", []))
            if keyword in src:
                return cell
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [f"## {keyword}\n"]
    }

# 1. Colab badge (Markdown)
colab_badge = find_markdown_cell("colab-badge.svg")
new_cells.append(colab_badge)

# 2. Intro markdown
intro = find_markdown_cell("E-PATH-CO-REASON: Production-Grade Google Colab Training Notebook")
new_cells.append(intro)

# 3. Config header markdown
config_hdr = find_markdown_cell("Central Experiment Configuration Block")
new_cells.append(config_hdr)

# 4. Central Config code block
config_block = find_code_cell("CENTRAL EXPERIMENT CONFIGURATION BLOCK")
new_cells.append(config_block)

# 5. Repo setup header markdown
setup_hdr = find_markdown_cell("Automatic Repository Setup")
new_cells.append(setup_hdr)

# 6. Repo setup code block
repo_setup_source = [
    "# ==========================================\n",
    "# SECTION 1 & 3: REPOSITORY DETECT & IMPORT CHECKS\n",
    "# ==========================================\n",
    "import os\n",
    "import sys\n",
    "from pathlib import Path\n",
    "\n",
    "# 1. Detect if in Google Colab\n",
    "is_colab = False\n",
    "try:\n",
    "    import google.colab\n",
    "    is_colab = True\n",
    "except ImportError:\n",
    "    pass\n",
    "\n",
    "if is_colab:\n",
    "    repo_name = \"MediTriageAI\"\n",
    "    expected_repo_root = Path(\"/content\") / repo_name\n",
    "    if not expected_repo_root.exists():\n",
    "        REPO_URL = \"https://github.com/ROHAN-BHUTANI/MediTriageAI.git\"\n",
    "        print(f\"Cloning fresh repository: {REPO_URL} on branch '{EXPERIMENT_CONFIG[\"git_branch\"]}'...\")\n",
    "        !git clone -b {EXPERIMENT_CONFIG[\"git_branch\"]} {REPO_URL} {expected_repo_root}\n",
    "    repo_root = expected_repo_root.resolve()\n",
    "else:\n",
    "    def find_repo_root(start_dir: Path) -> Path:\n",
    "        for parent in [start_dir] + list(start_dir.parents):\n",
    "            if (parent / \".git\").exists() or (parent / \"requirements.txt\").exists():\n",
    "                return parent\n",
    "        return start_dir\n",
    "    repo_root = find_repo_root(Path(os.getcwd()).resolve())\n",
    "\n",
    "os.chdir(repo_root)\n",
    "\n",
    "if str(repo_root) not in sys.path:\n",
    "    sys.path.insert(0, str(repo_root))\n",
    "\n",
    "print(f\"Current Working Directory: {os.getcwd()}\")\n",
    "print(f\"Repository Root:           {repo_root}\")\n",
    "print(f\"sys.path[0]:               {sys.path[0]}\")\n",
    "\n",
    "req_path = repo_root / \"requirements.txt\"\n",
    "if req_path.exists():\n",
    "    print(f\"Installing dependencies from: {req_path}\")\n",
    "    !pip install -q -r {req_path}\n",
    "else:\n",
    "    print(f\"Warning: requirements.txt not found at {req_path}. Performing fallback install...\")\n",
    "    !pip install -q transformers scikit-learn matplotlib seaborn pandas numpy torch psutil\n",
    "\n",
    "print(\"Validating imports and workspace modules...\")\n",
    "required_imports = [\n",
    "    (\"torch\", \"torch\"),\n",
    "    (\"transformers\", \"transformers\"),\n",
    "    (\"pandas\", \"pandas\"),\n",
    "    (\"numpy\", \"numpy\"),\n",
    "    (\"sklearn\", \"scikit-learn\"),\n",
    "    (\"matplotlib\", \"matplotlib\"),\n",
    "    (\"seaborn\", \"seaborn\"),\n",
    "    (\"psutil\", \"psutil\"),\n",
    "    (\"models.emergent_path_triage.model\", \"E-PATH-CO-REASON Model\"),\n",
    "    (\"src.data_pipeline\", \"E-PATH-CO-REASON Data Pipeline\"),\n",
    "    (\"src.trainer\", \"E-PATH-CO-REASON Trainer\")\n",
    "]\n",
    "\n",
    "missing = []\n",
    "for mod_name, friendly_name in required_imports:\n",
    "    try:\n",
    "        __import__(mod_name)\n",
    "        print(f\"  ✓ {mod_name} imported successfully.\")\n",
    "    except ImportError as e:\n",
    "        print(f\"  ✗ Failed to import {mod_name}: {e}\")\n",
    "        missing.append(friendly_name)\n",
    "\n",
    "if missing:\n",
    "    raise ImportError(f\"Verification failed. Missing required components: {missing}\")\n",
    "print(\"All imports validated successfully.\")\n"
]
new_cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {
        "id": "repo_setup_cell"
    },
    "outputs": [],
    "source": repo_setup_source
})

# 7. Env validation header markdown
env_hdr = find_markdown_cell("Environment Validation")
new_cells.append(env_hdr)

# 8. NEW: Env validation & consolidated Health Report code block
env_val_source = [
    "# ==========================================\n",
    "# SECTION 2: ENVIRONMENT VALIDATION & HEALTH REPORT\n",
    "# ==========================================\n",
    "import json\n",
    "import sys\n",
    "import torch\n",
    "import psutil\n",
    "import pandas as pd\n",
    "import transformers\n",
    "from src.data_pipeline import detect_colab_environment\n",
    "\n",
    "env_meta = detect_colab_environment()\n",
    "has_gpu = env_meta[\"has_gpu\"]\n",
    "gpu_name = env_meta[\"gpu_name\"]\n",
    "total_vram = 0\n",
    "free_vram = 0\n",
    "\n",
    "if has_gpu:\n",
    "    t = torch.cuda.get_device_properties(0).total_memory\n",
    "    a = torch.cuda.memory_allocated(0)\n",
    "    total_vram = t / (1024 ** 3)\n",
    "    free_vram = (t - a) / (1024 ** 3)\n",
    "\n",
    "git_commit = \"N/A\"\n",
    "try:\n",
    "    import subprocess\n",
    "    git_commit = subprocess.check_output([\"git\", \"rev-parse\", \"HEAD\"], cwd=str(repo_root)).decode(\"utf-8\").strip()\n",
    "except Exception:\n",
    "    pass\n",
    "\n",
    "env_info = {\n",
    "    \"python_version\": sys.version,\n",
    "    \"pytorch_version\": torch.__version__,\n",
    "    \"cuda_version\": torch.version.cuda if has_gpu else \"N/A\",\n",
    "    \"transformers_version\": transformers.__version__,\n",
    "    \"gpu_model\": gpu_name,\n",
    "    \"total_gpu_memory_gb\": total_vram,\n",
    "    \"available_gpu_memory_gb\": free_vram,\n",
    "    \"cpu_cores\": psutil.cpu_count(logical=True),\n",
    "    \"ram_gb\": psutil.virtual_memory().total / (1024 ** 3),\n",
    "    \"git_commit_hash\": git_commit\n",
    "}\n",
    "\n",
    "print(\"ENVIRONMENT AUDIT LOG:\")\n",
    "print(json.dumps(env_info, indent=4))\n",
    "\n",
    "# PRINT NOTEBOOK HEALTH REPORT\n",
    "def print_notebook_health_report():\n",
    "    print(\"=\"*60)\n",
    "    print(\"E-PATH-CO-REASON NOTEBOOK HEALTH REPORT\")\n",
    "    print(\"=\"*60)\n",
    "    print(f\"  Repository Commit    : {env_info['git_commit_hash']}\")\n",
    "    print(f\"  PyTorch Version      : {env_info['pytorch_version']}\")\n",
    "    print(f\"  CUDA Version         : {env_info['cuda_version']}\")\n",
    "    print(f\"  GPU Model            : {env_info['gpu_model']}\")\n",
    "    \n",
    "    # Dataset rows\n",
    "    dataset_rows = \"N/A\"\n",
    "    config = globals().get(\"EXPERIMENT_CONFIG\", None)\n",
    "    if config:\n",
    "        dataset_csv = repo_root / config[\"dataset_relative_path\"]\n",
    "        if dataset_csv.exists():\n",
    "            try:\n",
    "                df = pd.read_csv(dataset_csv)\n",
    "                dataset_rows = len(df)\n",
    "            except Exception:\n",
    "                pass\n",
    "    print(f\"  Dataset Total Rows   : {dataset_rows}\")\n",
    "    \n",
    "    # Experiment / Checkpoint dirs\n",
    "    exp_dir = \"N/A\"\n",
    "    ckpt_dir = \"N/A\"\n",
    "    dirs = globals().get(\"dirs\", None)\n",
    "    if dirs:\n",
    "        exp_dir = str(dirs.get(\"experiments\", \"N/A\"))\n",
    "        ckpt_dir = str(dirs.get(\"checkpoints\", \"N/A\"))\n",
    "    elif config:\n",
    "        is_colab = False\n",
    "        try:\n",
    "            import google.colab\n",
    "            is_colab = True\n",
    "        except ImportError:\n",
    "            pass\n",
    "        drive_base = Path(config[\"drive_workspace_dir\"]) if config[\"use_drive\"] and is_colab else repo_root\n",
    "        exp_base = drive_base / \"experiments\" / config[\"experiment_name\"]\n",
    "        exp_dir = str(exp_base)\n",
    "        ckpt_dir = str(exp_base / \"checkpoints\")\n",
    "        \n",
    "    print(f\"  Experiment Directory : {exp_dir}\")\n",
    "    print(f\"  Checkpoint Directory : {ckpt_dir}\")\n",
    "    print(\"=\"*60)\n",
    "\n",
    "print_notebook_health_report()\n"
]
new_cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {
        "id": "health_report_cell"
    },
    "outputs": [],
    "source": env_val_source
})

# 9. Drive mount header markdown
drive_hdr = find_markdown_cell("Google Drive Mount")
new_cells.append(drive_hdr)

# 10. Drive mount code block
drive_block_source = [
    "# ==========================================\n",
    "# SECTION 3: DRIVE MOUNT & FOLDERS VERIFICATION\n",
    "# ==========================================\n",
    "from pathlib import Path\n",
    "import json\n",
    "import sys\n",
    "import os\n",
    "\n",
    "try:\n",
    "    from google.colab import drive\n",
    "    drive.mount(\"/content/drive\")\n",
    "    DRIVE_AVAILABLE = True\n",
    "except Exception as e:\n",
    "    print(f\"Drive mount failed: {e}\")\n",
    "    print(\"Using local /content workspace instead.\")\n",
    "    DRIVE_AVAILABLE = False\n",
    "\n",
    "# -------------------------\n",
    "# Workspace selection\n",
    "# -------------------------\n",
    "if DRIVE_AVAILABLE:\n",
    "    drive_base = Path(EXPERIMENT_CONFIG[\"drive_workspace_dir\"])\n",
    "else:\n",
    "    # Resolve repo_root dynamically if Cell 10 was skipped\n",
    "    if 'repo_root' not in globals() and 'repo_root' not in locals():\n",
    "        def find_repo_root(start_dir: Path) -> Path:\n",
    "            for parent in [start_dir] + list(start_dir.parents):\n",
    "                if (parent / \".git\").exists() or (parent / \"requirements.txt\").exists():\n",
    "                    return parent\n",
    "            return start_dir\n",
    "        repo_root = find_repo_root(Path(os.getcwd()).resolve())\n",
    "    drive_base = repo_root\n",
    "\n",
    "print(f\"Workspace: {drive_base}\")\n",
    "\n",
    "exp_base = drive_base / \"experiments\" / EXPERIMENT_CONFIG[\"experiment_name\"]\n",
    "\n",
    "dirs = {\n",
    "    \"experiments\": exp_base,\n",
    "    \"checkpoints\": exp_base / \"checkpoints\",\n",
    "    \"logs\": exp_base / \"logs\",\n",
    "    \"figures\": exp_base / \"figures\",\n",
    "    \"exports\": exp_base / \"exports\"\n",
    "}\n",
    "\n",
    "for name, path in dirs.items():\n",
    "    path.mkdir(parents=True, exist_ok=True)\n",
    "    print(f\"Verified folder '{name}': {path}\")\n",
    "\n",
    "# Write permission check\n",
    "test_file = exp_base / \"write_check.txt\"\n",
    "try:\n",
    "    test_file.write_text(\"write check successful\")\n",
    "    test_file.unlink()\n",
    "    print(\"Write permissions successfully verified.\")\n",
    "except Exception as e:\n",
    "    raise PermissionError(f\"Target folder is not writable: {e}\")\n",
    "\n",
    "# Save environment.json with auto-recovery if skipped Cell 12\n",
    "if 'env_info' in globals() or 'env_info' in locals():\n",
    "    target_env = env_info\n",
    "else:\n",
    "    import torch\n",
    "    import psutil\n",
    "    import transformers\n",
    "    has_gpu = torch.cuda.is_available()\n",
    "    target_env = {\n",
    "        \"python_version\": sys.version,\n",
    "        \"pytorch_version\": torch.__version__,\n",
    "        \"cuda_version\": torch.version.cuda if has_gpu else \"N/A\",\n",
    "        \"transformers_version\": transformers.__version__,\n",
    "        \"gpu_model\": torch.cuda.get_device_name(0) if has_gpu else \"N/A\",\n",
    "        \"total_gpu_memory_gb\": torch.cuda.get_device_properties(0).total_memory / (1024 ** 3) if has_gpu else 0,\n",
    "        \"available_gpu_memory_gb\": 0,\n",
    "        \"cpu_cores\": psutil.cpu_count(logical=True),\n",
    "        \"ram_gb\": psutil.virtual_memory().total / (1024 ** 3),\n",
    "        \"git_commit_hash\": \"N/A\"\n",
    "    }\n",
    "with open(dirs[\"logs\"] / \"environment.json\", \"w\", encoding=\"utf-8\") as f:\n",
    "    json.dump(target_env, f, indent=4)\n"
]
new_cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {
        "id": "drive_mount_cell"
    },
    "outputs": [],
    "source": drive_block_source
})

# 11. Dataset validation header markdown
dataset_hdr = find_markdown_cell("Dataset Validation Checks")
new_cells.append(dataset_hdr)

# 12. Dataset validation code block
dataset_block = find_code_cell("DATASET VALIDATION")
new_cells.append(dataset_block)

# 13. NEW: Recovery Execution Guide (Markdown)
guide_source = [
    "# E-PATH-CO-REASON Recovery Execution Guide\n",
    "\n",
    "This guide details the exact cell execution sequences required for different research tasks on a fresh or resumed Google Colab runtime:\n",
    "\n",
    "### (A) Fresh Training from Scratch\n",
    "Run all cells in sequence from top to bottom:\n",
    "1. **Section 1**: Central Experiment Configuration Block (Cell 3)\n",
    "2. **Section 2**: Automatic Repository Setup & Import Validation (Cell 10)\n",
    "3. **Section 3**: Environment Validation & Health Report (Cell 12)\n",
    "4. **Section 4**: Google Drive Mount & Workspace Setup (Cell 14)\n",
    "5. **Section 5**: Dataset Validation Checks (Cell 16)\n",
    "6. **Section 6**: Training Initialization & Fit (Cell 17)\n",
    "7. **Section 8**: Post-Training Evaluation Exports\n",
    "8. **Section 9**: Final Experiment Summary Report\n",
    "\n",
    "### (B) Runtime Reset (Resuming Interrupted Training)\n",
    "If your runtime gets disconnected during active training, run:\n",
    "1. **Section 1**: Central Experiment Configuration Block (Cell 3)\n",
    "2. **Section 2**: Automatic Repository Setup & Import Validation (Cell 10)\n",
    "3. **Section 4**: Google Drive Mount & Workspace Setup (Cell 14)\n",
    "4. **Section 6**: Training Initialization & Fit (Cell 17)\n",
    "   * *Note: The fit cell automatically detects the checkpoint `latest_model.pt` in Drive and resumes from the exact epoch state.*\n",
    "5. **Section 8 & Section 9** (Evaluation & Summary)\n",
    "\n",
    "### (C) Evaluation Only (No Retraining)\n",
    "If training is complete and you only want to evaluate `best_model.pt` on a fresh runtime:\n",
    "1. **Section 1**: Central Experiment Configuration Block (Cell 3)\n",
    "2. **Section 2**: Automatic Repository Setup & Import Validation (Cell 10)\n",
    "3. **Section 4**: Google Drive Mount & Workspace Setup (Cell 14)\n",
    "4. **Section 8**: Post-Training Evaluation Exports\n",
    "   * *Note: Section 8 automatically invokes `recover_runtime()` to reconstruct all data structures and loaders from configuration and checkpoints without retraining.*\n",
    "5. **Section 9**: Final Experiment Summary Report\n",
    "\n",
    "### (D) Report Regeneration / Plot Re-rendering\n",
    "If any export file or plot is missing or deleted:\n",
    "1. **Section 1**: Central Experiment Configuration Block (Cell 3)\n",
    "2. **Section 2**: Automatic Repository Setup & Import Validation (Cell 10)\n",
    "3. **Section 4**: Google Drive Mount & Workspace Setup (Cell 14)\n",
    "4. **Section 8**: Post-Training Evaluation Exports\n",
    "   * *Note: Section 8 checks for missing exports and regenerates only the missing files dynamically.*\n"
]
new_cells.append({
    "cell_type": "markdown",
    "metadata": {
        "id": "recovery_execution_guide_cell"
    },
    "source": guide_source
})

# 14. Training init header markdown
train_init_hdr = find_markdown_cell("Training Initialization & Checkpoint Resume Loop")
new_cells.append(train_init_hdr)

# 15. Training init & fit code block
training_fit_source = [
    "# ==========================================\n",
    "# SECTION 6: TRAINING INITIALIZATION & FIT\n",
    "# ==========================================\n",
    "import json\n",
    "import torch\n",
    "from pathlib import Path\n",
    "from models.emergent_path_triage.model import EmergentPathTriageConfig, EmergentPathTriageModel\n",
    "from src.data_pipeline import TokenizerPipeline, EmergentTriageDataset, get_dataloader, get_leakage_safe_splits\n",
    "\n",
    "def configure_model_freezes(model, checkpoint_path):\n",
    "    if checkpoint_path and Path(checkpoint_path).exists():\n",
    "        try:\n",
    "            ckpt = torch.load(checkpoint_path, map_location=\"cpu\", weights_only=False)\n",
    "            if \"optimizer_state_dict\" in ckpt and \"param_groups\" in ckpt[\"optimizer_state_dict\"]:\n",
    "                num_groups = len(ckpt[\"optimizer_state_dict\"][\"param_groups\"])\n",
    "                if num_groups == 1:\n",
    "                    print(\"Checkpoint was trained with frozen encoder. Freezing encoder parameters for alignment.\")\n",
    "                    for name, param in model.named_parameters():\n",
    "                        if \"encoder\" in name:\n",
    "                            param.requires_grad = False\n",
    "                else:\n",
    "                    print(f\"Checkpoint was trained with {num_groups} optimizer groups. Leaving encoder parameters unfrozen.\")\n",
    "        except Exception as e:\n",
    "            print(f\"Warning during model freeze configuration: {e}\")\n",
    "\n",
    "print(\"Preparing dataloaders...\")\n",
    "if EXPERIMENT_CONFIG[\"max_samples\"] is not None:\n",
    "    df = df.sample(EXPERIMENT_CONFIG[\"max_samples\"], random_state=EXPERIMENT_CONFIG[\"seed\"])\n",
    "\n",
    "train_df, val_df, test_df = get_leakage_safe_splits(\n",
    "    df,\n",
    "    train_ratio=EXPERIMENT_CONFIG[\"train_ratio\"],\n",
    "    val_ratio=EXPERIMENT_CONFIG[\"val_ratio\"],\n",
    "    seed=EXPERIMENT_CONFIG[\"seed\"],\n",
    "    stratify=False\n",
    ")\n",
    "\n",
    "pipeline = TokenizerPipeline(tokenizer, max_length=EXPERIMENT_CONFIG[\"max_length\"])\n",
    "\n",
    "def create_ds(target_df):\n",
    "    texts = target_df[\"text\"].tolist()\n",
    "    spec_ids = [validator.validate_specialist(str(c)) for c in target_df[\"department_code\"]]\n",
    "    sev_ids = [validator.validate_severity(str(l)) for l in target_df[\"severity_heuristic\"]]\n",
    "    return EmergentTriageDataset(texts, spec_ids, sev_ids, pipeline)\n",
    "\n",
    "train_loader = get_dataloader(create_ds(train_df), batch_size=EXPERIMENT_CONFIG[\"batch_size\"], shuffle=True)\n",
    "val_loader = get_dataloader(create_ds(val_df), batch_size=EXPERIMENT_CONFIG[\"batch_size\"], shuffle=False)\n",
    "test_loader = get_dataloader(create_ds(test_df), batch_size=EXPERIMENT_CONFIG[\"batch_size\"], shuffle=False)\n",
    "\n",
    "print(\"Building model...\")\n",
    "config = EmergentPathTriageConfig(latent_dim=8)\n",
    "model_meta = EmergentPathTriageModel()\n",
    "model = model_meta.build(None, triage_config=config)\n",
    "\n",
    "# Configure model freezes dynamically before trainer creation\n",
    "latest_ckpt = dirs[\"checkpoints\"] / \"latest_model.pt\"\n",
    "checkpoint_to_check = latest_ckpt if latest_ckpt.exists() else None\n",
    "configure_model_freezes(model, checkpoint_to_check)\n",
    "\n",
    "from src.trainer import EmergentTrainer, EmergentTrainerConfig\n",
    "trainer_cfg = EmergentTrainerConfig(\n",
    "    epochs=EXPERIMENT_CONFIG[\"epochs\"],\n",
    "    learning_rate=EXPERIMENT_CONFIG[\"learning_rate\"],\n",
    "    encoder_lr=EXPERIMENT_CONFIG[\"encoder_lr\"],\n",
    "    weight_decay=EXPERIMENT_CONFIG[\"weight_decay\"],\n",
    "    gradient_clipping=EXPERIMENT_CONFIG[\"gradient_clipping\"],\n",
    "    gradient_accumulation_steps=EXPERIMENT_CONFIG[\"gradient_accumulation_steps\"],\n",
    "    use_amp=EXPERIMENT_CONFIG[\"use_amp\"],\n",
    "    early_stopping_patience=EXPERIMENT_CONFIG[\"early_stopping_patience\"],\n",
    "    early_stopping_metric=EXPERIMENT_CONFIG[\"early_stopping_metric\"],\n",
    "    early_stopping_min_improvement=EXPERIMENT_CONFIG[\"early_stopping_min_improvement\"],\n",
    "    warmup_ratio=EXPERIMENT_CONFIG[\"warmup_ratio\"],\n",
    "    seed=EXPERIMENT_CONFIG[\"seed\"],\n",
    "    optimizer_type=EXPERIMENT_CONFIG[\"optimizer_type\"],\n",
    "    scheduler_type=EXPERIMENT_CONFIG[\"scheduler_type\"],\n",
    "    checkpoint_dir=str(dirs[\"checkpoints\"])\n",
    ")\n",
    "\n",
    "trainer = EmergentTrainer(\n",
    "    model=model,\n",
    "    config=trainer_cfg,\n",
    "    train_loader=train_loader,\n",
    "    val_loader=val_loader,\n",
    "    tokenizer=tokenizer\n",
    ")\n",
    "trainer.checkpoint_dir = dirs[\"checkpoints\"]\n",
    "\n",
    "# Checkpoint Resume loop check\n",
    "if latest_ckpt.exists():\n",
    "    print(f\"==================================================\")\n",
    "    print(f\"Checkpoint discovered: {latest_ckpt}. Resuming run...\")\n",
    "    print(f\"==================================================\")\n",
    "    trainer.load_checkpoint(latest_ckpt)\n",
    "else:\n",
    "    print(f\"==================================================\")\n",
    "    print(f\"No checkpoint found under checkpoints/. Initiating new training.\")\n",
    "    print(f\"==================================================\")\n",
    "\n",
    "best_val_metrics = trainer.fit()"
]
new_cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {
        "id": "epath_co_reason_training_fit"
    },
    "outputs": [],
    "source": training_fit_source
})

# 16. Evaluation header markdown
eval_hdr = find_markdown_cell("Post-Training Evaluation Exports")
new_cells.append(eval_hdr)

# 17. Hardened Evaluation & Exports block
new_eval_source = [
    "# ==========================================\n",
    "# SECTION 8: EVALUATION METRICS & CONFUSION PLOTS (WITH RUNTIME RECOVERY)\n",
    "# ==========================================\n",
    "import os\n",
    "import sys\n",
    "import json\n",
    "import shutil\n",
    "from pathlib import Path\n",
    "import datetime\n",
    "import torch\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from sklearn.metrics import confusion_matrix, precision_recall_fscore_support, accuracy_score\n",
    "from transformers import AutoTokenizer\n",
    "from models.emergent_path_triage.model import EmergentPathTriageConfig, EmergentPathTriageModel\n",
    "from src.data_pipeline import TokenizerPipeline, EmergentTriageDataset, get_dataloader, get_leakage_safe_splits, LabelValidator\n",
    "from src.trainer import EmergentTrainer, EmergentTrainerConfig\n",
    "\n",
    "def find_best_checkpoint(drive_workspace_dir, repo_root):\n",
    "    is_colab = False\n",
    "    try:\n",
    "        import google.colab\n",
    "        is_colab = True\n",
    "    except ImportError:\n",
    "        pass\n",
    "    drive_base = Path(drive_workspace_dir) if is_colab else repo_root\n",
    "    exp_dir = drive_base / \"experiments\"\n",
    "    checkpoints = []\n",
    "    if exp_dir.exists():\n",
    "        for exp_folder in exp_dir.iterdir():\n",
    "            if exp_folder.is_dir():\n",
    "                ckpt_file = exp_folder / \"checkpoints\" / \"best_model.pt\"\n",
    "                if ckpt_file.exists():\n",
    "                    mtime = ckpt_file.stat().st_mtime\n",
    "                    checkpoints.append((exp_folder.name, ckpt_file, mtime))\n",
    "    if not checkpoints:\n",
    "        local_exp_dir = repo_root / \"experiments\"\n",
    "        if local_exp_dir.exists():\n",
    "            for exp_folder in local_exp_dir.iterdir():\n",
    "                if exp_folder.is_dir():\n",
    "                    ckpt_file = exp_folder / \"checkpoints\" / \"best_model.pt\"\n",
    "                    if ckpt_file.exists():\n",
    "                        mtime = ckpt_file.stat().st_mtime\n",
    "                        checkpoints.append((exp_folder.name, ckpt_file, mtime))\n",
    "    if not checkpoints:\n",
    "        raise FileNotFoundError(\"No 'best_model.pt' checkpoint discovered under experiments/**/checkpoints/\")\n",
    "    checkpoints.sort(key=lambda x: x[2], reverse=True)\n",
    "    return checkpoints[0]\n",
    "\n",
    "def validate_checkpoint(ckpt_path):\n",
    "    try:\n",
    "        checkpoint = torch.load(ckpt_path, map_location=\"cpu\", weights_only=False)\n",
    "    except Exception as e:\n",
    "        raise RuntimeError(f\"Checkpoint Loading Failed: The file at {ckpt_path} is corrupt or not a valid PyTorch save file. Error: {e}\")\n",
    "    required_keys = [\"model_state_dict\", \"optimizer_state_dict\", \"history\", \"metadata\"]\n",
    "    missing_keys = [k for k in required_keys if k not in checkpoint]\n",
    "    if missing_keys:\n",
    "        raise KeyError(f\"Checkpoint Validation Failed: The checkpoint at {ckpt_path} is missing critical components: {missing_keys}.\")\n",
    "    print(\"Checkpoint contents successfully validated.\")\n",
    "    return checkpoint\n",
    "\n",
    "def recover_runtime(experiment_name=None):\n",
    "    \"\"\"\n",
    "    Reconstructs all variables required for E-PATH-CO-REASON evaluation\n",
    "    after a session reset or runtime restart.\n",
    "    \"\"\"\n",
    "    # Redefine helper functions inside recover_runtime scoping\n",
    "    def _find_best_checkpoint(drive_workspace_dir, repo_root):\n",
    "        is_colab = False\n",
    "        try:\n",
    "            import google.colab\n",
    "            is_colab = True\n",
    "        except ImportError:\n",
    "            pass\n",
    "        drive_base = Path(drive_workspace_dir) if is_colab else repo_root\n",
    "        exp_dir = drive_base / \"experiments\"\n",
    "        checkpoints = []\n",
    "        if exp_dir.exists():\n",
    "            for exp_folder in exp_dir.iterdir():\n",
    "                if exp_folder.is_dir():\n",
    "                    ckpt_file = exp_folder / \"checkpoints\" / \"best_model.pt\"\n",
    "                    if ckpt_file.exists():\n",
    "                        mtime = ckpt_file.stat().st_mtime\n",
    "                        checkpoints.append((exp_folder.name, ckpt_file, mtime))\n",
    "        if not checkpoints:\n",
    "            local_exp_dir = repo_root / \"experiments\"\n",
    "            if local_exp_dir.exists():\n",
    "                for exp_folder in local_exp_dir.iterdir():\n",
    "                    if exp_folder.is_dir():\n",
    "                        ckpt_file = exp_folder / \"checkpoints\" / \"best_model.pt\"\n",
    "                        if ckpt_file.exists():\n",
    "                            mtime = ckpt_file.stat().st_mtime\n",
    "                            checkpoints.append((exp_folder.name, ckpt_file, mtime))\n",
    "        if not checkpoints:\n",
    "            raise FileNotFoundError(\"No 'best_model.pt' checkpoint discovered under experiments/**/checkpoints/\")\n",
    "        checkpoints.sort(key=lambda x: x[2], reverse=True)\n",
    "        return checkpoints[0]\n",
    "\n",
    "    def _configure_model_freezes(model, checkpoint_path):\n",
    "        if checkpoint_path and Path(checkpoint_path).exists():\n",
    "            try:\n",
    "                ckpt = torch.load(checkpoint_path, map_location=\"cpu\", weights_only=False)\n",
    "                if \"optimizer_state_dict\" in ckpt and \"param_groups\" in ckpt[\"optimizer_state_dict\"]:\n",
    "                    num_groups = len(ckpt[\"optimizer_state_dict\"][\"param_groups\"])\n",
    "                    if num_groups == 1:\n",
    "                        print(\"Checkpoint was trained with frozen encoder. Freezing encoder parameters for alignment.\")\n",
    "                        for name, param in model.named_parameters():\n",
    "                            if \"encoder\" in name:\n",
    "                                param.requires_grad = False\n",
    "                    else:\n",
    "                        print(f\"Checkpoint was trained with {num_groups} optimizer groups. Leaving encoder parameters unfrozen.\")\n",
    "            except Exception as e:\n",
    "                print(f\"Warning during model freeze configuration: {e}\")\n",
    "\n",
    "    print(\"Reconstructing runtime environments...\")\n",
    "    def find_repo_root(start_dir: Path) -> Path:\n",
    "        for parent in [start_dir] + list(start_dir.parents):\n",
    "            if (parent / \".git\").exists() or (parent / \"requirements.txt\").exists():\n",
    "                return parent\n",
    "        return start_dir\n",
    "    repo_root = find_repo_root(Path(os.getcwd()).resolve())\n",
    "    os.chdir(repo_root)\n",
    "    if str(repo_root) not in sys.path:\n",
    "        sys.path.insert(0, str(repo_root))\n",
    "        \n",
    "    g_config = globals().get(\"EXPERIMENT_CONFIG\", None)\n",
    "    drive_workspace = g_config[\"drive_workspace_dir\"] if g_config else \"/content/drive/MyDrive/MediTriageAI\"\n",
    "    \n",
    "    # Checkpoint Discovery\n",
    "    try:\n",
    "        exp_name_found, best_ckpt_found, mtime_found = _find_best_checkpoint(drive_workspace, repo_root)\n",
    "        experiment_name = exp_name_found\n",
    "        best_ckpt_path = best_ckpt_found\n",
    "        timestamp = datetime.datetime.fromtimestamp(mtime_found).strftime('%Y-%m-%d %H:%M:%S')\n",
    "        print(\"=\"*50)\n",
    "        print(f\"Experiment selected : {experiment_name}\")\n",
    "        print(f\"Checkpoint path     : {best_ckpt_path}\")\n",
    "        print(f\"Training timestamp  : {timestamp}\")\n",
    "        print(\"=\"*50)\n",
    "    except FileNotFoundError:\n",
    "        experiment_name = g_config[\"experiment_name\"] if g_config else \"epath_co_reason_baseline\"\n",
    "        best_ckpt_path = None\n",
    "        \n",
    "    # Drive configuration\n",
    "    is_colab = False\n",
    "    try:\n",
    "        import google.colab\n",
    "        is_colab = True\n",
    "    except ImportError:\n",
    "        pass\n",
    "        \n",
    "    drive_base = Path(drive_workspace) if is_colab else repo_root\n",
    "    exp_base = drive_base / \"experiments\" / experiment_name\n",
    "    \n",
    "    # Load configuration.json if available\n",
    "    config_json = exp_base / \"logs\" / \"configuration.json\"\n",
    "    if config_json.exists():\n",
    "        with open(config_json, \"r\") as f:\n",
    "            config = json.load(f)\n",
    "    else:\n",
    "        config = g_config if g_config else {\n",
    "            \"experiment_name\": experiment_name,\n",
    "            \"git_branch\": \"main\",\n",
    "            \"dataset_relative_path\": \"meditriage/data/processed/dataset.csv\",\n",
    "            \"max_samples\": None,\n",
    "            \"max_length\": 128,\n",
    "            \"train_ratio\": 0.8,\n",
    "            \"val_ratio\": 0.1,\n",
    "            \"test_ratio\": 0.1,\n",
    "            \"epochs\": 10,\n",
    "            \"batch_size\": 32,\n",
    "            \"learning_rate\": 1e-4,\n",
    "            \"encoder_lr\": 2e-5,\n",
    "            \"weight_decay\": 0.01,\n",
    "            \"gradient_clipping\": 1.0,\n",
    "            \"gradient_accumulation_steps\": 1,\n",
    "            \"use_amp\": True,\n",
    "            \"seed\": 1337,\n",
    "            \"optimizer_type\": \"adamw\",\n",
    "            \"scheduler_type\": \"cosine\",\n",
    "            \"warmup_ratio\": 0.1,\n",
    "            \"early_stopping_patience\": 3,\n",
    "            \"early_stopping_metric\": \"val_loss\",\n",
    "            \"early_stopping_min_improvement\": 1e-4,\n",
    "            \"use_drive\": True,\n",
    "            \"drive_workspace_dir\": str(drive_base)\n",
    "        }\n",
    "        \n",
    "    dirs = {\n",
    "        \"experiments\": exp_base,\n",
    "        \"checkpoints\": exp_base / \"checkpoints\",\n",
    "        \"logs\": exp_base / \"logs\",\n",
    "        \"figures\": exp_base / \"figures\",\n",
    "        \"exports\": exp_base / \"exports\"\n",
    "    }\n",
    "    \n",
    "    for d in dirs.values():\n",
    "        d.mkdir(parents=True, exist_ok=True)\n",
    "        \n",
    "    tokenizer = AutoTokenizer.from_pretrained(\"xlm-roberta-base\")\n",
    "    validator = LabelValidator()\n",
    "    \n",
    "    dataset_csv = repo_root / config[\"dataset_relative_path\"]\n",
    "    df = pd.read_csv(dataset_csv)\n",
    "    if df[\"text\"].isna().sum() > 0:\n",
    "        df = df.dropna(subset=[\"text\"])\n",
    "    if config[\"max_samples\"] is not None:\n",
    "        df = df.sample(config[\"max_samples\"], random_state=config[\"seed\"])\n",
    "        \n",
    "    train_df, val_df, test_df = get_leakage_safe_splits(\n",
    "        df,\n",
    "        train_ratio=config[\"train_ratio\"],\n",
    "        val_ratio=config[\"val_ratio\"],\n",
    "        seed=config[\"seed\"],\n",
    "        stratify=False\n",
    "    )\n",
    "    pipeline = TokenizerPipeline(tokenizer, max_length=config[\"max_length\"])\n",
    "    \n",
    "    def create_ds(target_df):\n",
    "        texts = target_df[\"text\"].tolist()\n",
    "        spec_ids = [validator.validate_specialist(str(c)) for c in target_df[\"department_code\"]]\n",
    "        sev_ids = [validator.validate_severity(str(l)) for l in target_df[\"severity_heuristic\"]]\n",
    "        return EmergentTriageDataset(texts, spec_ids, sev_ids, pipeline)\n",
    "\n",
    "    train_loader = get_dataloader(create_ds(train_df), batch_size=config[\"batch_size\"], shuffle=True)\n",
    "    val_loader = get_dataloader(create_ds(val_df), batch_size=config[\"batch_size\"], shuffle=False)\n",
    "    test_loader = get_dataloader(create_ds(test_df), batch_size=config[\"batch_size\"], shuffle=False)\n",
    "    \n",
    "    triage_config = EmergentPathTriageConfig(latent_dim=8)\n",
    "    model_meta = EmergentPathTriageModel()\n",
    "    model = model_meta.build(None, triage_config=triage_config)\n",
    "    \n",
    "    # Align model parameters dynamically based on best checkpoint groups count\n",
    "    _configure_model_freezes(model, best_ckpt_path)\n",
    "    \n",
    "    trainer_cfg = EmergentTrainerConfig(\n",
    "        epochs=config[\"epochs\"],\n",
    "        learning_rate=config[\"learning_rate\"],\n",
    "        encoder_lr=config[\"encoder_lr\"],\n",
    "        weight_decay=config[\"weight_decay\"],\n",
    "        gradient_clipping=config[\"gradient_clipping\"],\n",
    "        gradient_accumulation_steps=config[\"gradient_accumulation_steps\"],\n",
    "        use_amp=config[\"use_amp\"],\n",
    "        early_stopping_patience=config[\"early_stopping_patience\"],\n",
    "        early_stopping_metric=config[\"early_stopping_metric\"],\n",
    "        early_stopping_min_improvement=config[\"early_stopping_min_improvement\"],\n",
    "        warmup_ratio=config[\"warmup_ratio\"],\n",
    "        seed=config[\"seed\"],\n",
    "        optimizer_type=config[\"optimizer_type\"],\n",
    "        scheduler_type=config[\"scheduler_type\"],\n",
    "        checkpoint_dir=str(dirs[\"checkpoints\"])\n",
    "    )\n",
    "    \n",
    "    trainer = EmergentTrainer(\n",
    "        model=model,\n",
    "        config=trainer_cfg,\n",
    "        train_loader=train_loader,\n",
    "        val_loader=val_loader,\n",
    "        tokenizer=tokenizer\n",
    "    )\n",
    "    trainer.checkpoint_dir = dirs[\"checkpoints\"]\n",
    "    \n",
    "    def fit_override(*args, **kwargs):\n",
    "        raise RuntimeError(\"CRITICAL ERROR: trainer.fit() was invoked during the evaluation flow! Training is strictly disabled during evaluation.\")\n",
    "    trainer.fit = fit_override\n",
    "    \n",
    "    return config, dirs, tokenizer, validator, train_loader, val_loader, test_loader, model, trainer\n",
    "\n",
    "# Perform Runtime Recovery\n",
    "config, dirs, tokenizer, validator, train_loader, val_loader, test_loader, model, trainer = recover_runtime()\n",
    "\n",
    "# Resolve Best Checkpoint Path\n",
    "g_config = globals().get(\"EXPERIMENT_CONFIG\", None)\n",
    "drive_workspace = g_config[\"drive_workspace_dir\"] if g_config else \"/content/drive/MyDrive/MediTriageAI\"\n",
    "def find_best_checkpoint_path():\n",
    "    try:\n",
    "        _, ckpt_path, _ = find_best_checkpoint(drive_workspace, Path(os.getcwd()).resolve())\n",
    "        return ckpt_path\n",
    "    except FileNotFoundError:\n",
    "        return dirs[\"checkpoints\"] / \"best_model.pt\"\n",
    "\n",
    "best_ckpt = find_best_checkpoint_path()\n",
    "\n",
    "# Self-Validation\n",
    "def perform_self_validation(tokenizer, validator, model, trainer, checkpoint_path, test_loader):\n",
    "    checks = {\n",
    "        \"Tokenizer instantiated\": tokenizer is not None,\n",
    "        \"Label Validator instantiated\": validator is not None,\n",
    "        \"Model instantiated\": model is not None,\n",
    "        \"Trainer instantiated\": trainer is not None,\n",
    "        \"Checkpoint file exists\": Path(checkpoint_path).exists() if checkpoint_path else False,\n",
    "        \"Checkpoint readable\": False,\n",
    "        \"Test loader not empty\": len(test_loader) > 0 if test_loader is not None else False\n",
    "    }\n",
    "    if checks[\"Checkpoint file exists\"]:\n",
    "        try:\n",
    "            validate_checkpoint(checkpoint_path)\n",
    "            checks[\"Checkpoint readable\"] = True\n",
    "        except Exception as e:\n",
    "            print(f\"Checkpoint validation check failed: {e}\")\n",
    "            checks[\"Checkpoint readable\"] = False\n",
    "            \n",
    "    print(\"\\n\" + \"=\"*50)\n",
    "    print(\"PRE-EVALUATION SELF-VALIDATION CHECKLIST:\")\n",
    "    print(\"=\"*50)\n",
    "    all_ok = True\n",
    "    for desc, passed in checks.items():\n",
    "        status = \"✓ PASSED\" if passed else \"✗ FAILED\"\n",
    "        print(f\"  {status:<10} | {desc}\")\n",
    "        if not passed:\n",
    "            all_ok = False\n",
    "    print(\"=\"*50)\n",
    "    \n",
    "    if not all_ok:\n",
    "        critical_failed = not (checks[\"Tokenizer instantiated\"] and checks[\"Label Validator instantiated\"] and checks[\"Model instantiated\"] and checks[\"Trainer instantiated\"] and checks[\"Checkpoint readable\"] and checks[\"Test loader not empty\"])\n",
    "        if critical_failed:\n",
    "            raise RuntimeError(\"CRITICAL SELF-VALIDATION FAILURE: One or more critical requirements failed. Aborting evaluation flow.\")\n",
    "    print(\"All critical self-validation checks passed successfully!\")\n",
    "\n",
    "perform_self_validation(tokenizer, validator, model, trainer, best_ckpt, test_loader)\n",
    "\n",
    "# Load best parameters checkpoint\n",
    "print(\"Loading best parameters checkpoint...\")\n",
    "trainer.load_checkpoint(best_ckpt)\n",
    "\n",
    "# Dynamically resolve best_val_metrics if it is missing\n",
    "if 'best_val_metrics' not in globals() or best_val_metrics is None:\n",
    "    if hasattr(trainer, 'history') and trainer.history:\n",
    "        best_val_metrics = min(trainer.history, key=lambda x: x.get(\"val_loss\", float('inf')))\n",
    "    else:\n",
    "        best_val_metrics = {\n",
    "            \"val_loss\": 0.0,\n",
    "            \"val_specialist_loss\": 0.0,\n",
    "            \"val_severity_loss\": 0.0,\n",
    "            \"val_cons_loss\": 0.0,\n",
    "            \"val_div_loss\": 0.0,\n",
    "            \"val_ortho_loss\": 0.0,\n",
    "            \"epoch\": \"N/A\"\n",
    "        }\n",
    "\n",
    "# Execute Evaluation Pass\n",
    "model.eval()\n",
    "all_spec_labels = []\n",
    "all_sev_labels = []\n",
    "all_spec_preds = []\n",
    "all_sev_preds = []\n",
    "all_routing_probs = []\n",
    "\n",
    "with torch.no_grad():\n",
    "    for batch in test_loader:\n",
    "        input_ids = batch[\"input_ids\"].to(trainer.device)\n",
    "        attention_mask = batch[\"attention_mask\"].to(trainer.device)\n",
    "        labels_spec = batch[\"labels_specialist\"]\n",
    "        labels_sev = batch[\"labels_severity\"]\n",
    "\n",
    "        outputs = model(input_ids, attention_mask)\n",
    "\n",
    "        spec_preds = outputs.specialist_logits.argmax(dim=-1).cpu().numpy()\n",
    "        sev_preds = outputs.severity_logits.argmax(dim=-1).cpu().numpy()\n",
    "\n",
    "        all_spec_labels.extend(labels_spec.numpy())\n",
    "        all_sev_labels.extend(labels_sev.numpy())\n",
    "        all_spec_preds.extend(spec_preds)\n",
    "        all_sev_preds.extend(sev_preds)\n",
    "\n",
    "        if model._last_routing_decision is not None:\n",
    "            all_routing_probs.append(model._last_routing_decision.routing_probabilities.cpu().numpy())\n",
    "\n",
    "spec_acc = accuracy_score(all_spec_labels, all_spec_preds)\n",
    "spec_p, spec_r, spec_f1, _ = precision_recall_fscore_support(all_spec_labels, all_spec_preds, average=\"macro\", zero_division=0)\n",
    "sev_acc = accuracy_score(all_sev_labels, all_sev_preds)\n",
    "sev_p, sev_r, sev_f1, _ = precision_recall_fscore_support(all_sev_labels, all_sev_preds, average=\"macro\", zero_division=0)\n",
    "\n",
    "# Check and regenerate all expected outputs\n",
    "def verify_and_regenerate_exports(dirs, trainer, validator, model, test_loader, spec_acc, spec_p, spec_r, spec_f1, sev_acc, sev_p, sev_r, sev_f1, best_val_metrics, all_spec_labels, all_spec_preds, all_sev_labels, all_sev_preds, all_routing_probs):\n",
    "    exports_dir = dirs[\"exports\"]\n",
    "    figures_dir = dirs[\"figures\"]\n",
    "    \n",
    "    required_files = {\n",
    "        \"metrics.json\": exports_dir / \"metrics.json\",\n",
    "        \"routing_statistics.json\": exports_dir / \"routing_statistics.json\",\n",
    "        \"training_history.csv\": exports_dir / \"training_history.csv\",\n",
    "        \"validation_history.csv\": exports_dir / \"validation_history.csv\",\n",
    "        \"loss_curves.png\": figures_dir / \"loss_curves.png\",\n",
    "        \"accuracy_curves.png\": figures_dir / \"accuracy_curves.png\",\n",
    "        \"specialist_confusion_matrix.png\": figures_dir / \"specialist_confusion_matrix.png\",\n",
    "        \"severity_confusion_matrix.png\": figures_dir / \"severity_confusion_matrix.png\"\n",
    "    }\n",
    "    \n",
    "    missing = [name for name, path in required_files.items() if not path.exists()]\n",
    "    if not missing:\n",
    "        print(\"All expected export files verified successfully.\")\n",
    "        return\n",
    "        \n",
    "    print(f\"Missing exports detected: {missing}. Regenerating missing files...\")\n",
    "    history = getattr(trainer, 'history', [])\n",
    "    history_df = pd.DataFrame(history)\n",
    "    \n",
    "    for name in missing:\n",
    "        if name == \"metrics.json\":\n",
    "            metrics_export = {\n",
    "                \"specialist\": {\n",
    "                    \"accuracy\": float(spec_acc),\n",
    "                    \"macro_precision\": float(spec_p),\n",
    "                    \"macro_recall\": float(spec_r),\n",
    "                    \"macro_f1\": float(spec_f1)\n",
    "                },\n",
    "                \"severity\": {\n",
    "                    \"accuracy\": float(sev_acc),\n",
    "                    \"macro_precision\": float(sev_p),\n",
    "                    \"macro_recall\": float(sev_r),\n",
    "                    \"macro_f1\": float(sev_f1)\n",
    "                },\n",
    "                \"overall_losses\": {\n",
    "                    \"val_loss\": float(best_val_metrics[\"val_loss\"]),\n",
    "                    \"val_specialist_loss\": float(best_val_metrics[\"val_specialist_loss\"]),\n",
    "                    \"val_severity_loss\": float(best_val_metrics[\"val_severity_loss\"]),\n",
    "                    \"val_cons_loss\": float(best_val_metrics[\"val_cons_loss\"]),\n",
    "                    \"val_div_loss\": float(best_val_metrics[\"val_div_loss\"]),\n",
    "                    \"val_ortho_loss\": float(best_val_metrics[\"val_ortho_loss\"])\n",
    "                }\n",
    "            }\n",
    "            with open(required_files[\"metrics.json\"], \"w\") as f:\n",
    "                json.dump(metrics_export, f, indent=4)\n",
    "            print(\"Regenerated metrics.json\")\n",
    "            \n",
    "        elif name == \"routing_statistics.json\":\n",
    "            if all_routing_probs:\n",
    "                all_probs = np.concatenate(all_routing_probs, axis=0)\n",
    "                B_t, M_t, N_t = all_probs.shape\n",
    "                epsilon = 1e-9\n",
    "                entropies = -np.sum(all_probs * np.log(all_probs + epsilon), axis=-1)\n",
    "                util_argmax = all_probs.argmax(axis=-1)\n",
    "                utilization_counts = [np.bincount(util_argmax[:, s], minlength=N_t).tolist() for s in range(M_t)]\n",
    "                routing_export = {\n",
    "                    \"mean_routing_entropy\": float(entropies.mean()),\n",
    "                    \"entropy_per_step\": entropies.mean(axis=0).tolist(),\n",
    "                    \"ctb_utilizations_per_step\": utilization_counts,\n",
    "                    \"average_reasoning_depth\": M_t,\n",
    "                    \"mean_confidence\": float(np.max(all_probs, axis=-1).mean())\n",
    "                }\n",
    "                with open(required_files[\"routing_statistics.json\"], \"w\") as f:\n",
    "                    json.dump(routing_export, f, indent=4)\n",
    "                print(\"Regenerated routing_statistics.json\")\n",
    "                \n",
    "        elif name == \"training_history.csv\":\n",
    "            if not history_df.empty:\n",
    "                history_df.to_csv(required_files[\"training_history.csv\"], index=False)\n",
    "                print(\"Regenerated training_history.csv\")\n",
    "                \n",
    "        elif name == \"validation_history.csv\":\n",
    "            if not history_df.empty:\n",
    "                val_cols = [c for c in history_df.columns if \"val_\" in c or c in [\"epoch\", \"time\"]]\n",
    "                history_df[val_cols].to_csv(required_files[\"validation_history.csv\"], index=False)\n",
    "                print(\"Regenerated validation_history.csv\")\n",
    "                \n",
    "        elif name == \"loss_curves.png\":\n",
    "            if not history_df.empty:\n",
    "                plt.figure(figsize=(10, 5))\n",
    "                plt.plot(history_df[\"epoch\"], history_df[\"train_loss\"], label=\"Train Loss\", marker=\"o\")\n",
    "                plt.plot(history_df[\"epoch\"], history_df[\"val_loss\"], label=\"Val Loss\", marker=\"x\")\n",
    "                plt.title(\"E-PATH-CO-REASON Loss Curves\")\n",
    "                plt.xlabel(\"Epoch\")\n",
    "                plt.ylabel(\"Loss\")\n",
    "                plt.grid(True)\n",
    "                plt.legend()\n",
    "                plt.savefig(required_files[\"loss_curves.png\"])\n",
    "                plt.close()\n",
    "                print(\"Regenerated loss_curves.png\")\n",
    "                \n",
    "        elif name == \"accuracy_curves.png\":\n",
    "            if not history_df.empty:\n",
    "                plt.figure(figsize=(10, 5))\n",
    "                plt.plot(history_df[\"epoch\"], history_df[\"train_specialist_acc\"], label=\"Train Spec Acc\", marker=\"o\")\n",
    "                plt.plot(history_df[\"epoch\"], history_df[\"val_specialist_acc\"], label=\"Val Spec Acc\", marker=\"x\")\n",
    "                plt.plot(history_df[\"epoch\"], history_df[\"train_severity_acc\"], label=\"Train Sev Acc\", marker=\"s\")\n",
    "                plt.plot(history_df[\"epoch\"], history_df[\"val_severity_acc\"], label=\"Val Sev Acc\", marker=\"d\")\n",
    "                plt.title(\"E-PATH-CO-REASON Accuracy Curves\")\n",
    "                plt.xlabel(\"Epoch\")\n",
    "                plt.ylabel(\"Accuracy\")\n",
    "                plt.grid(True)\n",
    "                plt.legend()\n",
    "                plt.savefig(required_files[\"accuracy_curves.png\"])\n",
    "                plt.close()\n",
    "                print(\"Regenerated accuracy_curves.png\")\n",
    "                \n",
    "        elif name == \"specialist_confusion_matrix.png\":\n",
    "            plt.figure(figsize=(10, 8))\n",
    "            sns.heatmap(confusion_matrix(all_spec_labels, all_spec_preds), annot=True, fmt=\"d\", cmap=\"Blues\",\n",
    "                        xticklabels=validator.specialist_classes, yticklabels=validator.specialist_classes)\n",
    "            plt.title(\"Specialist Confusion Matrix\")\n",
    "            plt.savefig(required_files[\"specialist_confusion_matrix.png\"])\n",
    "            plt.close()\n",
    "            print(\"Regenerated specialist_confusion_matrix.png\")\n",
    "            \n",
    "        elif name == \"severity_confusion_matrix.png\":\n",
    "            plt.figure(figsize=(8, 6))\n",
    "            sns.heatmap(confusion_matrix(all_sev_labels, all_sev_preds), annot=True, fmt=\"d\", cmap=\"Oranges\",\n",
    "                        xticklabels=validator.severity_labels, yticklabels=validator.severity_labels)\n",
    "            plt.title(\"Severity Confusion Matrix\")\n",
    "            plt.savefig(required_files[\"severity_confusion_matrix.png\"])\n",
    "            plt.close()\n",
    "            print(\"Regenerated severity_confusion_matrix.png\")\n",
    "\n",
    "verify_and_regenerate_exports(dirs, trainer, validator, model, test_loader, spec_acc, spec_p, spec_r, spec_f1, sev_acc, sev_p, sev_r, sev_f1, best_val_metrics, all_spec_labels, all_spec_preds, all_sev_labels, all_sev_preds, all_routing_probs)\n",
    "\n",
    "shutil.copyfile(dirs[\"checkpoints\"] / \"best_model.pt\", dirs[\"experiments\"] / \"best_model.pt\")\n",
    "shutil.copyfile(dirs[\"checkpoints\"] / \"latest_model.pt\", dirs[\"experiments\"] / \"latest_model.pt\")\n",
    "\n",
    "print(\"Post-training assets successfully compiled, verified, and exported.\")"
]
new_cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {
        "id": "epath_co_reason_evaluation_exports"
    },
    "outputs": [],
    "source": new_eval_source
})

# 18. Summary markdown header
summary_hdr = find_markdown_cell("Final Experiment Summary Report")
new_cells.append(summary_hdr)

# 19. Hardened summary code block
new_summary_source = [
    "# ==========================================\n",
    "# SECTION 9: FINAL EXPERIMENT SUMMARY\n",
    "# ==========================================\n",
    "if 'dirs' not in globals() or 'EXPERIMENT_CONFIG' not in globals() or 'spec_acc' not in globals():\n",
    "    config, dirs, tokenizer, validator, train_loader, val_loader, test_loader, model, trainer = recover_runtime()\n",
    "    if hasattr(trainer, 'history') and trainer.history:\n",
    "        best_val_metrics = min(trainer.history, key=lambda x: x.get(\"val_loss\", float('inf')))\n",
    "    else:\n",
    "        best_val_metrics = {\"epoch\": \"N/A\"}\n",
    "    metrics_json = dirs[\"exports\"] / \"metrics.json\"\n",
    "    if metrics_json.exists():\n",
    "        with open(metrics_json, \"r\") as f:\n",
    "            m_exp = json.load(f)\n",
    "        spec_acc = m_exp[\"specialist\"][\"accuracy\"]\n",
    "        sev_acc = m_exp[\"severity\"][\"accuracy\"]\n",
    "        spec_f1 = m_exp[\"specialist\"][\"macro_f1\"]\n",
    "        sev_f1 = m_exp[\"severity\"][\"macro_f1\"]\n",
    "    else:\n",
    "        spec_acc, sev_acc, spec_f1, sev_f1 = 0.0, 0.0, 0.0, 0.0\n",
    "else:\n",
    "    config = EXPERIMENT_CONFIG\n",
    "        \n",
    "if 'env_info' not in globals():\n",
    "    env_json = dirs[\"logs\"] / \"environment.json\"\n",
    "    if env_json.exists():\n",
    "        with open(env_json, \"r\") as f:\n",
    "            env_info = json.load(f)\n",
    "    else:\n",
    "        env_info = {\"gpu_model\": \"Unknown (Session Reset)\"}\n",
    "\n",
    "print(f\"==================================================\")\n",
    "print(f\"FINAL EXPERIMENT SUMMARY REPORT\")\n",
    "print(f\"==================================================\")\n",
    "print(f\"Experiment Name      : {config['experiment_name']}\")\n",
    "print(f\"GPU Model Used       : {env_info['gpu_model']}\")\n",
    "print(f\"Best Training Epoch  : {best_val_metrics.get('epoch', 'N/A')}\")\n",
    "print(f\"Specialist Accuracy  : {spec_acc:.2%}\")\n",
    "print(f\"Severity Accuracy    : {sev_acc:.2%}\")\n",
    "print(f\"Specialist F1-Score  : {spec_f1:.2%}\")\n",
    "print(f\"Severity F1-Score    : {sev_f1:.2%}\")\n",
    "print(f\"--------------------------------------------------\")\n",
    "print(f\"Outputs Directory Locations:\")\n",
    "print(f\"- Checkpoints        : {dirs['checkpoints']}\")\n",
    "print(f\"- Exported Reports   : {dirs['exports']}\")\n",
    "print(f\"- Plot Figures       : {dirs['figures']}\")\n",
    "print(f\"==================================================\")"
]
new_cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {
        "id": "epath_co_reason_final_summary"
    },
    "outputs": [],
    "source": new_summary_source
})

# 20. Diagnostics markdown header
new_cells.append({
    "cell_type": "markdown",
    "metadata": {
        "id": "epath_co_reason_debug_section"
    },
    "source": [
        "## 10. Diagnostics, Utilities, & Custom Colab Checks\n",
        "\n",
        "This section aggregates interactive checks, path mappings, and repository structures verified during training."
    ]
})

# 20.1 Dtype trace header
new_cells.append({
    "cell_type": "markdown",
    "metadata": {
        "id": "epath_co_reason_dtype_trace_hdr"
    },
    "source": [
        "### 10.1. Full Dtype Trace & Dtype Contract Validation"
    ]
})

# 20.2 Dtype trace code cell
dtype_trace_source = [
    "# ==========================================\n",
    "# SECTION 10.1: FULL DTYPE TRACE & CONTRACT VALIDATION\n",
    "# ==========================================\n",
    "import json\n",
    "import torch\n",
    "from pathlib import Path\n",
    "from src.model import JointLoss\n",
    "\n",
    "def run_dtype_trace_and_validate():\n",
    "    print(\"=\"*60)\n",
    "    print(\"RUNNING FULL DTYPE TRACE & CONTRACT VALIDATION\")\n",
    "    print(\"=\"*60)\n",
    "    \n",
    "    # 1. Recover model and trainer\n",
    "    if 'model' not in globals() or 'trainer' not in globals() or 'test_loader' not in globals():\n",
    "        print(\"Reconstructing runtime components...\")\n",
    "        config, dirs, tokenizer, validator, train_loader, val_loader, test_loader, model, trainer = recover_runtime()\n",
    "    else:\n",
    "        model = globals()['model']\n",
    "        trainer = globals()['trainer']\n",
    "        test_loader = globals()['test_loader']\n",
    "        dirs = globals()['dirs']\n",
    "        \n",
    "    # Get a batch\n",
    "    batch = next(iter(test_loader))\n",
    "    \n",
    "    # Trace store\n",
    "    trace = {}\n",
    "    hooks = []\n",
    "    \n",
    "    def make_hook(name):\n",
    "        def hook(module, input, output):\n",
    "            in_dtypes = []\n",
    "            if name == \"Encoder\":\n",
    "                if len(input) > 0 and isinstance(input[0], torch.Tensor):\n",
    "                    in_dtypes.append(str(input[0].dtype))\n",
    "            elif name == \"Evidence Synthesizer\":\n",
    "                if len(input) > 0 and isinstance(input[0], torch.Tensor):\n",
    "                    in_dtypes.append(str(input[0].dtype))\n",
    "            elif name == \"Router\":\n",
    "                evidence = input[0]\n",
    "                if hasattr(evidence, \"symptom\"):\n",
    "                    in_dtypes.append(str(evidence.symptom.dtype))\n",
    "            elif \"Thought Block\" in name:\n",
    "                if len(input) > 0 and isinstance(input[0], torch.Tensor):\n",
    "                    in_dtypes.append(str(input[0].dtype))\n",
    "            elif name == \"Execution Engine\":\n",
    "                ev_list = input[0]\n",
    "                if isinstance(ev_list, list):\n",
    "                    for x in ev_list:\n",
    "                        if isinstance(x, torch.Tensor):\n",
    "                            in_dtypes.append(str(x.dtype))\n",
    "            elif name in [\"Consistency Projection\", \"Prediction Heads (Specialist)\", \"Prediction Heads (Severity)\"]:\n",
    "                if len(input) > 0 and isinstance(input[0], torch.Tensor):\n",
    "                    in_dtypes.append(str(input[0].dtype))\n",
    "            else:\n",
    "                if isinstance(input, tuple):\n",
    "                    for x in input:\n",
    "                        if isinstance(x, torch.Tensor):\n",
    "                            in_dtypes.append(str(x.dtype))\n",
    "                elif isinstance(input, torch.Tensor):\n",
    "                    in_dtypes.append(str(input.dtype))\n",
    "                    \n",
    "            out_dtypes = []\n",
    "            if name == \"Encoder\":\n",
    "                if hasattr(output, \"last_hidden_state\"):\n",
    "                    out_dtypes.append(str(output.last_hidden_state.dtype))\n",
    "            elif name == \"Evidence Synthesizer\":\n",
    "                if hasattr(output, \"symptom\"):\n",
    "                    out_dtypes.append(str(output.symptom.dtype))\n",
    "            elif name == \"Router\":\n",
    "                if hasattr(output, \"routing_probabilities\"):\n",
    "                    out_dtypes.append(str(output.routing_probabilities.dtype))\n",
    "            elif \"Thought Block\" in name:\n",
    "                if isinstance(output, torch.Tensor):\n",
    "                    out_dtypes.append(str(output.dtype))\n",
    "                elif isinstance(output, tuple) and len(output) > 0 and isinstance(output[0], torch.Tensor):\n",
    "                    out_dtypes.append(str(output[0].dtype))\n",
    "            elif name == \"Execution Engine\":\n",
    "                if isinstance(output, tuple) and len(output) > 0 and isinstance(output[0], torch.Tensor):\n",
    "                    out_dtypes.append(str(output[0].dtype))\n",
    "            elif name == \"Consistency Projection\":\n",
    "                if isinstance(output, tuple):\n",
    "                    for x in output:\n",
    "                        if isinstance(x, torch.Tensor):\n",
    "                            out_dtypes.append(str(x.dtype))\n",
    "            elif name in [\"Prediction Heads (Specialist)\", \"Prediction Heads (Severity)\"]:\n",
    "                if isinstance(output, torch.Tensor):\n",
    "                    out_dtypes.append(str(output.dtype))\n",
    "            else:\n",
    "                if isinstance(output, tuple):\n",
    "                    for x in output:\n",
    "                        if isinstance(x, torch.Tensor):\n",
    "                            out_dtypes.append(str(x.dtype))\n",
    "                elif isinstance(output, torch.Tensor):\n",
    "                    out_dtypes.append(str(output.dtype))\n",
    "                    \n",
    "            trace[name] = {\n",
    "                \"input_dtypes\": in_dtypes,\n",
    "                \"output_dtypes\": out_dtypes\n",
    "            }\n",
    "        return hook\n",
    "\n",
    "    # Register hooks\n",
    "    hooks.append(model.encoder.register_forward_hook(make_hook(\"Encoder\")))\n",
    "    hooks.append(model.dces.register_forward_hook(make_hook(\"Evidence Synthesizer\")))\n",
    "    hooks.append(model.router.register_forward_hook(make_hook(\"Router\")))\n",
    "    for idx, block in enumerate(model.blocks):\n",
    "        hooks.append(block.register_forward_hook(make_hook(f\"Thought Block {idx + 1}\")))\n",
    "    hooks.append(model.engine.register_forward_hook(make_hook(\"Execution Engine\")))\n",
    "    hooks.append(model.dcp.register_forward_hook(make_hook(\"Consistency Projection\")))\n",
    "    hooks.append(model.classifier_specialist.register_forward_hook(make_hook(\"Prediction Heads (Specialist)\")))\n",
    "    hooks.append(model.classifier_severity.register_forward_hook(make_hook(\"Prediction Heads (Severity)\")))\n",
    "    hooks.append(model.register_forward_hook(make_hook(\"Model Top Level\")))\n",
    "\n",
    "    # Run forward pass under autocast matching trainer AMP state\n",
    "    model.eval()\n",
    "    device_type = \"cuda\" if next(model.parameters()).device.type == \"cuda\" else \"cpu\"\n",
    "    \n",
    "    with torch.no_grad():\n",
    "        with torch.amp.autocast(device_type=device_type, enabled=trainer.use_amp):\n",
    "            input_ids = batch[\"input_ids\"].to(next(model.parameters()).device)\n",
    "            attention_mask = batch[\"attention_mask\"].to(next(model.parameters()).device)\n",
    "            outputs = model(input_ids, attention_mask)\n",
    "            \n",
    "            # Compute loss\n",
    "            labels_spec = batch[\"labels_specialist\"].to(next(model.parameters()).device)\n",
    "            labels_sev = batch[\"labels_severity\"].to(next(model.parameters()).device)\n",
    "            loss_fn = JointLoss()\n",
    "            loss_dict = model.compute_loss(\n",
    "                outputs.specialist_logits,\n",
    "                outputs.severity_logits,\n",
    "                labels_spec,\n",
    "                labels_sev,\n",
    "                loss_fn\n",
    "            )\n",
    "            trace[\"Loss Computation\"] = {\n",
    "                \"input_dtypes\": [str(outputs.specialist_logits.dtype), str(outputs.severity_logits.dtype)],\n",
    "                \"output_dtypes\": [str(loss_dict[\"joint_loss\"].dtype)]\n",
    "            }\n",
    "            \n",
    "    # Remove hooks\n",
    "    for h in hooks:\n",
    "        h.remove()\n",
    "        \n",
    "    # Check DType Contract\n",
    "    contract_results = {}\n",
    "    def check_rule(name, key, expected, actual_list):\n",
    "        if not actual_list:\n",
    "            contract_results[f\"{name}_{key}\"] = f\"Fail: Output empty\"\n",
    "            return False\n",
    "        passed = all(expected in a for a in actual_list)\n",
    "        contract_results[f\"{name}_{key}\"] = \"Pass\" if passed else f\"Fail: expected {expected}, got {actual_list}\"\n",
    "        return passed\n",
    "\n",
    "    all_passed = True\n",
    "    \n",
    "    if trainer.use_amp:\n",
    "        all_passed &= check_rule(\"Encoder\", \"outputs\", \"float16\", trace[\"Encoder\"][\"output_dtypes\"])\n",
    "    else:\n",
    "        all_passed &= check_rule(\"Encoder\", \"outputs\", \"float32\", trace[\"Encoder\"][\"output_dtypes\"])\n",
    "        \n",
    "    all_passed &= check_rule(\"Evidence Synthesizer\", \"inputs\", \"float32\", trace[\"Evidence Synthesizer\"][\"input_dtypes\"])\n",
    "    all_passed &= check_rule(\"Evidence Synthesizer\", \"outputs\", \"float32\", trace[\"Evidence Synthesizer\"][\"output_dtypes\"])\n",
    "    all_passed &= check_rule(\"Router\", \"inputs\", \"float32\", trace[\"Router\"][\"input_dtypes\"])\n",
    "    all_passed &= check_rule(\"Router\", \"outputs\", \"float32\", trace[\"Router\"][\"output_dtypes\"])\n",
    "    all_passed &= check_rule(\"Execution Engine\", \"inputs\", \"float32\", trace[\"Execution Engine\"][\"input_dtypes\"])\n",
    "    all_passed &= check_rule(\"Execution Engine\", \"outputs\", \"float32\", trace[\"Execution Engine\"][\"output_dtypes\"])\n",
    "    \n",
    "    for idx in range(len(model.blocks)):\n",
    "        block_name = f\"Thought Block {idx+1}\"\n",
    "        if block_name in trace:\n",
    "            all_passed &= check_rule(block_name, \"inputs\", \"float32\", trace[block_name][\"input_dtypes\"])\n",
    "            all_passed &= check_rule(block_name, \"outputs\", \"float32\", trace[block_name][\"output_dtypes\"])\n",
    "        else:\n",
    "            contract_results[f\"{block_name}_inputs\"] = \"Skipped (Not Routed)\"\n",
    "            contract_results[f\"{block_name}_outputs\"] = \"Skipped (Not Routed)\"\n",
    "    all_passed &= check_rule(\"Consistency Projection\", \"inputs\", \"float32\", trace[\"Consistency Projection\"][\"input_dtypes\"])\n",
    "    all_passed &= check_rule(\"Consistency Projection\", \"outputs\", \"float32\", trace[\"Consistency Projection\"][\"output_dtypes\"])\n",
    "    all_passed &= check_rule(\"Prediction Heads (Specialist)\", \"inputs\", \"float32\", trace[\"Prediction Heads (Specialist)\"][\"input_dtypes\"])\n",
    "    \n",
    "    # Save Report\n",
    "    report = {\n",
    "        \"contract_checks\": contract_results,\n",
    "        \"full_trace\": trace,\n",
    "        \"amp_enabled\": trainer.use_amp,\n",
    "        \"device\": str(next(model.parameters()).device),\n",
    "        \"validation_passed\": all_passed\n",
    "    }\n",
    "    \n",
    "    report_path = dirs[\"exports\"] / \"dtype_report.json\"\n",
    "    with open(report_path, \"w\", encoding=\"utf-8\") as f:\n",
    "        json.dump(report, f, indent=4)\n",
    "        \n",
    "    print(f\"Contract Checks Status: {'SUCCESS' if all_passed else 'FAILED'}\")\n",
    "    print(json.dumps(contract_results, indent=4))\n",
    "    print(f\"Exported dtype_report.json to {report_path}\")\n",
    "    \n",
    "    if not all_passed:\n",
    "        raise ValueError(f\"DType Contract Violation detected: {contract_results}\")\n",
    "\n",
    "run_dtype_trace_and_validate()\n"
]
new_cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {
        "id": "epath_co_reason_dtype_trace_cell"
    },
    "outputs": [],
    "source": dtype_trace_source
})

# 20.3 Training dry run header
new_cells.append({
    "cell_type": "markdown",
    "metadata": {
        "id": "epath_co_reason_train_dryrun_hdr"
    },
    "source": [
        "### 10.2. Single-Step Training Dry Run"
    ]
})

# 20.4 Training dry run code cell
train_dryrun_source = [
    "# ==========================================\n",
    "# SECTION 10.2: TRAINING DRY RUN\n",
    "# ==========================================\n",
    "import json\n",
    "import torch\n",
    "from src.model import JointLoss\n",
    "\n",
    "def run_training_dry_run():\n",
    "    print(\"=\"*60)\n",
    "    print(\"RUNNING TRAINING DRY RUN (ONE OPTIMIZATION STEP)\")\n",
    "    print(\"=\"*60)\n",
    "    \n",
    "    if 'model' not in globals() or 'trainer' not in globals() or 'train_loader' not in globals():\n",
    "        print(\"Reconstructing runtime components...\")\n",
    "        config, dirs, tokenizer, validator, train_loader, val_loader, test_loader, model, trainer = recover_runtime()\n",
    "    else:\n",
    "        model = globals()['model']\n",
    "        trainer = globals()['trainer']\n",
    "        train_loader = globals()['train_loader']\n",
    "        dirs = globals()['dirs']\n",
    "        \n",
    "    batch = next(iter(train_loader))\n",
    "    model.train()\n",
    "    trainer.optimizer.zero_grad()\n",
    "    \n",
    "    device = trainer.device\n",
    "    input_ids = batch[\"input_ids\"].to(device)\n",
    "    attention_mask = batch[\"attention_mask\"].to(device)\n",
    "    labels_spec = batch[\"labels_specialist\"].to(device)\n",
    "    labels_sev = batch[\"labels_severity\"].to(device)\n",
    "    \n",
    "    device_type = \"cuda\" if device.type == \"cuda\" else \"cpu\"\n",
    "    \n",
    "    try:\n",
    "        with torch.amp.autocast(device_type=device_type, enabled=trainer.use_amp):\n",
    "            outputs = model(input_ids, attention_mask)\n",
    "            \n",
    "            from models.emergent_path_triage.hooks import apply_loss_hook\n",
    "            loss_fn = JointLoss()\n",
    "            loss_dict = apply_loss_hook(\n",
    "                model,\n",
    "                outputs.specialist_logits,\n",
    "                outputs.severity_logits,\n",
    "                labels_spec,\n",
    "                labels_sev,\n",
    "                loss_fn\n",
    "            )\n",
    "            loss = loss_dict[\"joint_loss\"]\n",
    "            \n",
    "        trainer.scaler.scale(loss).backward()\n",
    "        trainer.scaler.step(trainer.optimizer)\n",
    "        trainer.scaler.update()\n",
    "        \n",
    "        if trainer.scheduler is not None:\n",
    "            trainer.scheduler.step()\n",
    "            \n",
    "        validation_status = {\n",
    "            \"status\": \"Success\",\n",
    "            \"loss_value\": float(loss.item()),\n",
    "            \"device\": str(device),\n",
    "            \"amp_enabled\": trainer.use_amp,\n",
    "            \"scaler_scale\": float(trainer.scaler.get_scale()) if hasattr(trainer.scaler, 'get_scale') else 1.0\n",
    "        }\n",
    "        print(\"Training dry run completed successfully!\")\n",
    "    except Exception as e:\n",
    "        validation_status = {\n",
    "            \"status\": \"Failed\",\n",
    "            \"error\": str(e)\n",
    "        }\n",
    "        print(f\"Training dry run failed: {e}\")\n",
    "        raise e\n",
    "        \n",
    "    report_path = dirs[\"exports\"] / \"runtime_validation.json\"\n",
    "    with open(report_path, \"w\", encoding=\"utf-8\") as f:\n",
    "        json.dump(validation_status, f, indent=4)\n",
    "    print(f\"Exported runtime_validation.json to {report_path}\")\n",
    "\n",
    "run_training_dry_run()\n"
]
new_cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {
        "id": "epath_co_reason_train_dryrun_cell"
    },
    "outputs": [],
    "source": train_dryrun_source
})

# 20.5 Recovery dry run header
new_cells.append({
    "cell_type": "markdown",
    "metadata": {
        "id": "epath_co_reason_recovery_dryrun_hdr"
    },
    "source": [
        "### 10.3. Session Recovery & Evaluation Dry Run"
    ]
})

# 20.6 Recovery dry run code cell
recovery_dryrun_source = [
    "# ==========================================\n",
    "# SECTION 10.3: RECOVERY DRY RUN\n",
    "# ==========================================\n",
    "import json\n",
    "import torch\n",
    "from src.model import JointLoss\n",
    "\n",
    "def run_recovery_dry_run():\n",
    "    print(\"=\"*60)\n",
    "    print(\"RUNNING RECOVERY DRY RUN (SIMULATING FRESH NAMESPACE)\")\n",
    "    print(\"=\"*60)\n",
    "    \n",
    "    config, dirs, tokenizer, validator, train_loader, val_loader, test_loader, model, trainer = recover_runtime()\n",
    "    \n",
    "    best_ckpt = dirs[\"checkpoints\"] / \"best_model.pt\"\n",
    "    if not best_ckpt.exists():\n",
    "        best_ckpt = dirs[\"experiments\"] / \"best_model.pt\"\n",
    "        \n",
    "    print(f\"Simulating evaluation recovery from: {best_ckpt}\")\n",
    "    trainer.load_checkpoint(best_ckpt)\n",
    "    \n",
    "    model.eval()\n",
    "    batch = next(iter(test_loader))\n",
    "    \n",
    "    device = trainer.device\n",
    "    input_ids = batch[\"input_ids\"].to(device)\n",
    "    attention_mask = batch[\"attention_mask\"].to(device)\n",
    "    labels_spec = batch[\"labels_specialist\"].to(device)\n",
    "    labels_sev = batch[\"labels_severity\"].to(device)\n",
    "    \n",
    "    device_type = \"cuda\" if device.type == \"cuda\" else \"cpu\"\n",
    "    \n",
    "    try:\n",
    "        with torch.no_grad():\n",
    "            with torch.amp.autocast(device_type=device_type, enabled=trainer.use_amp):\n",
    "                outputs = model(input_ids, attention_mask)\n",
    "                loss_fn = JointLoss()\n",
    "                loss_dict = model.compute_loss(\n",
    "                    outputs.specialist_logits,\n",
    "                    outputs.severity_logits,\n",
    "                    labels_spec,\n",
    "                    labels_sev,\n",
    "                    loss_fn\n",
    "                )\n",
    "                \n",
    "        eval_status = {\n",
    "            \"status\": \"Success\",\n",
    "            \"eval_loss\": float(loss_dict[\"joint_loss\"].item()),\n",
    "            \"device\": str(device),\n",
    "            \"amp_enabled\": trainer.use_amp\n",
    "        }\n",
    "        print(\"Evaluation recovery step run completed successfully!\")\n",
    "    except Exception as e:\n",
    "        eval_status = {\n",
    "            \"status\": \"Failed\",\n",
    "            \"error\": str(e)\n",
    "        }\n",
    "        print(f\"Evaluation recovery dry run failed: {e}\")\n",
    "        raise e\n",
    "        \n",
    "    checkpoint_val_path = dirs[\"exports\"] / \"checkpoint_validation.json\"\n",
    "    recovery_val_path = dirs[\"exports\"] / \"recovery_validation.json\"\n",
    "    health_report_path = dirs[\"exports\"] / \"health_report.json\"\n",
    "    \n",
    "    with open(checkpoint_val_path, \"w\", encoding=\"utf-8\") as f:\n",
    "        json.dump(eval_status, f, indent=4)\n",
    "        \n",
    "    with open(recovery_val_path, \"w\", encoding=\"utf-8\") as f:\n",
    "        json.dump({\"recovery_status\": \"Success\", \"checkpoint_used\": str(best_ckpt)}, f, indent=4)\n",
    "        \n",
    "    health_report = {\n",
    "        \"cuda_available\": torch.cuda.is_available(),\n",
    "        \"device_name\": torch.cuda.get_device_name(0) if torch.cuda.is_available() else \"CPU\",\n",
    "        \"pytorch_version\": torch.__version__,\n",
    "        \"amp_supported\": trainer.env_meta[\"mixed_precision_available\"],\n",
    "        \"validation_passed\": True\n",
    "    }\n",
    "    with open(health_report_path, \"w\", encoding=\"utf-8\") as f:\n",
    "        json.dump(health_report, f, indent=4)\n",
    "        \n",
    "    print(f\"Exported checkpoint_validation.json to {checkpoint_val_path}\")\n",
    "    print(f\"Exported recovery_validation.json to {recovery_val_path}\")\n",
    "    print(f\"Exported health_report.json to {health_report_path}\")\n",
    "\n",
    "run_recovery_dry_run()\n"
]
new_cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {
        "id": "epath_co_reason_recovery_dryrun_cell"
    },
    "outputs": [],
    "source": recovery_dryrun_source
})

# Gather and relocate user interactive debugging checks
debug_keywords = ["!find", "!pwd", "!ls", "!grep", "!sed", "for var in ["]
for cell in cells:
    if cell.get("cell_type") == "code":
        src = "".join(cell.get("source", []))
        if any(kw in src for kw in debug_keywords) and "recover_runtime" not in src and "detect_colab_environment" not in src:
            new_cells.append(cell)

# Save
nb["cells"] = new_cells
with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent= 1)

print("Notebook production hardening pass successfully completed!")
